//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.product.get_product_reply_pdt1x1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.product.get_product_reply_pdt1x1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetProductReply_QNAME = new QName("http://ei/product/get_product_reply_pdt1x1", "GetProductReply");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.product.get_product_reply_pdt1x1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductReply }
     * 
     */
    public GetProductReply createGetProductReply() {
        return new GetProductReply();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/product/get_product_reply_pdt1x1", name = "GetProductReply")
    public JAXBElement<GetProductReply> createGetProductReply(GetProductReply value) {
        return new JAXBElement<GetProductReply>(_GetProductReply_QNAME, GetProductReply.class, null, value);
    }

}
