//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.document_reference_information;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for DocumentReferenceInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentReferenceInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentXML" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DocumentString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DocumentByte" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EncodingTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentReferenceInformation", namespace = "http://ei/core/document_reference_information", propOrder = {
    "documentXML",
    "documentString",
    "documentByte",
    "url",
    "contentTypeCode",
    "encodingTypeCode"
})
public class DocumentReferenceInformation {

    @XmlElement(name = "DocumentXML")
    protected DocumentReferenceInformation.DocumentXML documentXML;
    @XmlElement(name = "DocumentString")
    protected String documentString;
    @XmlElement(name = "DocumentByte")
    protected byte[] documentByte;
    @XmlElement(name = "URL")
    protected String url;
    @XmlElement(name = "ContentTypeCode")
    protected String contentTypeCode;
    @XmlElement(name = "EncodingTypeCode")
    protected String encodingTypeCode;

    /**
     * Gets the value of the documentXML property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceInformation.DocumentXML }
     *     
     */
    public DocumentReferenceInformation.DocumentXML getDocumentXML() {
        return documentXML;
    }

    /**
     * Sets the value of the documentXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceInformation.DocumentXML }
     *     
     */
    public void setDocumentXML(DocumentReferenceInformation.DocumentXML value) {
        this.documentXML = value;
    }

    /**
     * Gets the value of the documentString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentString() {
        return documentString;
    }

    /**
     * Sets the value of the documentString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentString(String value) {
        this.documentString = value;
    }

    /**
     * Gets the value of the documentByte property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDocumentByte() {
        return documentByte;
    }

    /**
     * Sets the value of the documentByte property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDocumentByte(byte[] value) {
        this.documentByte = ((byte[]) value);
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the contentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentTypeCode() {
        return contentTypeCode;
    }

    /**
     * Sets the value of the contentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentTypeCode(String value) {
        this.contentTypeCode = value;
    }

    /**
     * Gets the value of the encodingTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodingTypeCode() {
        return encodingTypeCode;
    }

    /**
     * Sets the value of the encodingTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodingTypeCode(String value) {
        this.encodingTypeCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class DocumentXML {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     {@link Element }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     {@link Element }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }

}
