<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/producer/producer_retrieval_prd2x6" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/producer/producer_retrieval_prd2x6_http" name="ProducerRetrievalPRD2X6Http" targetNamespace="http://ei/producer/producer_retrieval_prd2x6_http">
  <wsdl:import location="ProducerRetrievalPRD2X6.wsdl" namespace="http://ei/producer/producer_retrieval_prd2x6" />
  <wsdl:binding name="ProducerRetrievalPRD2X6HttpBinding" type="Port_0:ProducerRetrievalPRD2X6">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetProducer2X6">
      <soap:operation soapAction="GetProducer2X6" />
      <wsdl:input name="GetProducer2X6Request">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProducer2X6Response">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetProducerWithCommissionRates2X6">
      <soap:operation soapAction="GetProducerWithCommissionRates2X6" />
      <wsdl:input name="GetProducerWithCommissionRates2X6Request">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProducerWithCommissionRates2X6Response">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetProducerList2X6">
      <soap:operation soapAction="GetProducerList2X6" />
      <wsdl:input name="GetProducerList2X6Request">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProducerList2X6Response">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetFilteredProducerList2X6">
      <soap:operation soapAction="GetFilteredProducerList2X6" />
      <wsdl:input name="GetFilteredProducerList2X6Request">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetFilteredProducerList2X6Response">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProducerRetrievalPRD2X6HttpService">
    <wsdl:port binding="this:ProducerRetrievalPRD2X6HttpBinding" name="ProducerRetrievalPRD2X6HTTP_ProducerRetrievalPRD2X6HttpPort">
      <soap:address location="Contact ICC for ProducerRetrievalPRD2X6Http Endpoint" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>