//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.country.country_retrieval_crp10x1_http;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ei.core.country.Country;
import ei.corporate.get_country_list_reply_crp10x1.GetCountryListReply;
import ei.corporate.get_country_request_crp10x1.GetCountryRequest;

@WebService(name = "CountryRetrievalCRP10X1", targetNamespace = "http://ei/country/country_retrieval_crp10X1")
@XmlSeeAlso({
    ei.core.simplefault.ObjectFactory.class,
    ei.corporate.get_country_request_crp10x1.ObjectFactory.class,
    ei.core.territory.ObjectFactory.class,
    ei.core.country.ObjectFactory.class,
    ei.country.country_retrieval_crp10x1.ObjectFactory.class,
    ei.corporate.get_country_list_reply_crp10x1.ObjectFactory.class
})
public interface CountryRetrievalCRP10X1 {


    /**
     * 
     * @param asOfDate
     * @return
     *     returns ei.corporate.get_country_list_reply_crp10x1.GetCountryListReply
     * @throws GetCountryListSimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetCountryList", action = "GetCountryList")
    @WebResult(name = "GetCountryListReply", targetNamespace = "")
    @RequestWrapper(localName = "GetCountryList", targetNamespace = "http://ei/country/country_retrieval_crp10X1", className = "ei.country.country_retrieval_crp10x1.GetCountryList")
    @ResponseWrapper(localName = "GetCountryListResponse", targetNamespace = "http://ei/country/country_retrieval_crp10X1", className = "ei.country.country_retrieval_crp10x1.GetCountryListResponse")
    public GetCountryListReply getCountryList(
        @WebParam(name = "AsOfDate", targetNamespace = "")
        XMLGregorianCalendar asOfDate)
        throws GetCountryListSimpleFaultReplyMsg
    ;

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns ei.core.country.Country
     * @throws GetCountrySimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetCountry", action = "GetCountry")
    @WebResult(name = "Country", targetNamespace = "")
    @RequestWrapper(localName = "GetCountry", targetNamespace = "http://ei/country/country_retrieval_crp10X1", className = "ei.country.country_retrieval_crp10x1.GetCountry")
    @ResponseWrapper(localName = "GetCountryResponse", targetNamespace = "http://ei/country/country_retrieval_crp10X1", className = "ei.country.country_retrieval_crp10x1.GetCountryResponse")
    public Country getCountry(
        @WebParam(name = "GetCountryRequest", targetNamespace = "")
        GetCountryRequest getCountryRequest)
        throws GetCountrySimpleFaultReplyMsg
    ;

}
