//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ei/producer/get_producer_list_inputs_prd2x5")
package ei.producer.get_producer_list_inputs_prd2x5;
