//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.commercial_insured_group_with_policy_term;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.crm.commercial_insured_group.CommercialInsuredGroup;
import ei.crm.insured_with_policy_term.InsuredWithPolicyTerm;
import ei.crm.name_search_outputs_crm4x4.NameSearchOutputs;


/**
 * <p>Java class for CommercialInsuredGroupWithPolicyTerm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommercialInsuredGroupWithPolicyTerm">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ei/crm/commercial_insured_group}CommercialInsuredGroup">
 *       &lt;sequence>
 *         &lt;element name="InsuredWithPolicyTerm" type="{http://ei/crm/insured_with_policy_term}InsuredWithPolicyTerm" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommercialInsuredGroupWithPolicyTerm", namespace = "http://ei/crm/commercial_insured_group_with_policy_term", propOrder = {
    "insuredWithPolicyTerm"
})
public class CommercialInsuredGroupWithPolicyTerm
    extends CommercialInsuredGroup
{

    @XmlElement(name = "InsuredWithPolicyTerm")
    protected List<InsuredWithPolicyTerm> insuredWithPolicyTerm;

    /**
     * Gets the value of the insuredWithPolicyTerm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insuredWithPolicyTerm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInsuredWithPolicyTerm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InsuredWithPolicyTerm }
     * 
     * 
     */
    public List<InsuredWithPolicyTerm> getInsuredWithPolicyTerm() {
        if (insuredWithPolicyTerm == null) {
            insuredWithPolicyTerm = new ArrayList<InsuredWithPolicyTerm>();
        }
        return this.insuredWithPolicyTerm;
    }
    @Override
	public String toString() {
    	StringBuffer sb = new StringBuffer();
    	
    	List<InsuredWithPolicyTerm> insuredWithPolicyTermList = this.getInsuredWithPolicyTerm();
		if (insuredWithPolicyTermList.size()>3)
			insuredWithPolicyTermList = insuredWithPolicyTermList.subList(0, 2);
		
		for (InsuredWithPolicyTerm insuredWithPolicyTerm : insuredWithPolicyTermList)
    			{
    		
    				sb.append (", [ InsuredWithPolicyTerm :" + insuredWithPolicyTerm.toString() + "]");
    			}
    			
		return sb.toString();
	}
}
