//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package chubb_corporate.business.get_access_user_profile_list_reply_ebe4x1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import chubb_corporate.business.get_access_user_profile_list_outputs_ebe4x1.GetAccessUserProfileListOutputs;
import chubb_corporate.get_access.status_information.StatusInformation;


/**
 * <p>Java class for GetAccessUserProfileListReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetAccessUserProfileListReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetAccessUserProfileListOutputs" type="{http://chubb_corporate/business/get_access_user_profile_list_outputs_ebe4x1}GetAccessUserProfileListOutputs" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StatusInformation" type="{http://chubb_corporate/get_access/status_information}StatusInformation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAccessUserProfileListReply", namespace = "http://chubb_corporate/business/get_access_user_profile_list_reply_ebe4x1", propOrder = {
    "getAccessUserProfileListOutputs",
    "statusInformation"
})
public class GetAccessUserProfileListReply
    implements Serializable
{

    @XmlElement(name = "GetAccessUserProfileListOutputs")
    protected List<GetAccessUserProfileListOutputs> getAccessUserProfileListOutputs;
    @XmlElement(name = "StatusInformation")
    protected StatusInformation statusInformation;

    /**
     * Gets the value of the getAccessUserProfileListOutputs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getAccessUserProfileListOutputs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetAccessUserProfileListOutputs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetAccessUserProfileListOutputs }
     * 
     * 
     */
    public List<GetAccessUserProfileListOutputs> getGetAccessUserProfileListOutputs() {
        if (getAccessUserProfileListOutputs == null) {
            getAccessUserProfileListOutputs = new ArrayList<GetAccessUserProfileListOutputs>();
        }
        return this.getAccessUserProfileListOutputs;
    }

    /**
     * Gets the value of the statusInformation property.
     * 
     * @return
     *     possible object is
     *     {@link StatusInformation }
     *     
     */
    public StatusInformation getStatusInformation() {
        return statusInformation;
    }

    /**
     * Sets the value of the statusInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusInformation }
     *     
     */
    public void setStatusInformation(StatusInformation value) {
        this.statusInformation = value;
    }

}
