//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.insured_with_policy_term;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.crm.insured_with_policy_term package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InsuredWithPolicyTerm_QNAME = new QName("http://ei/crm/insured_with_policy_term", "InsuredWithPolicyTerm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.crm.insured_with_policy_term
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsuredWithPolicyTerm }
     * 
     */
    public InsuredWithPolicyTerm createInsuredWithPolicyTerm() {
        return new InsuredWithPolicyTerm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsuredWithPolicyTerm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/crm/insured_with_policy_term", name = "InsuredWithPolicyTerm")
    public JAXBElement<InsuredWithPolicyTerm> createInsuredWithPolicyTerm(InsuredWithPolicyTerm value) {
        return new JAXBElement<InsuredWithPolicyTerm>(_InsuredWithPolicyTerm_QNAME, InsuredWithPolicyTerm.class, null, value);
    }

}
