//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.insurerx1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This business object is information pertaining to the Chubb group.
 * 
 * <p>Java class for Insurer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Insurer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InsurerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsurerAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsurerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Insurer", namespace = "http://ei/core/insurerx1", propOrder = {
    "insurerName",
    "insurerAbbreviation",
    "insurerNumber"
})
public class Insurer {

    @XmlElement(name = "InsurerName")
    protected String insurerName;
    @XmlElement(name = "InsurerAbbreviation")
    protected String insurerAbbreviation;
    @XmlElement(name = "InsurerNumber")
    protected String insurerNumber;

    /**
     * Gets the value of the insurerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurerName() {
        return insurerName;
    }

    /**
     * Sets the value of the insurerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurerName(String value) {
        this.insurerName = value;
    }

    /**
     * Gets the value of the insurerAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurerAbbreviation() {
        return insurerAbbreviation;
    }

    /**
     * Sets the value of the insurerAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurerAbbreviation(String value) {
        this.insurerAbbreviation = value;
    }

    /**
     * Gets the value of the insurerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurerNumber() {
        return insurerNumber;
    }

    /**
     * Sets the value of the insurerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurerNumber(String value) {
        this.insurerNumber = value;
    }
    
    @Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("InsurerName: " + this.getInsurerName());
		sb.append(", InsurerAbbreviation: " + this.getInsurerAbbreviation());
		sb.append(", InsurerNumber: " + this.getInsurerNumber());
		
		
		
		return sb.toString();
	}

}
