//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.prdct_compnt_loss_value_option;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.core.prdct_compnt_loss_value_option package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PrdctCompntLossValueOption_QNAME = new QName("http://ei/core/prdct_compnt_loss_value_option", "PrdctCompntLossValueOption");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.core.prdct_compnt_loss_value_option
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrdctCompntLossValueOption }
     * 
     */
    public PrdctCompntLossValueOption createPrdctCompntLossValueOption() {
        return new PrdctCompntLossValueOption();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrdctCompntLossValueOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/core/prdct_compnt_loss_value_option", name = "PrdctCompntLossValueOption")
    public JAXBElement<PrdctCompntLossValueOption> createPrdctCompntLossValueOption(PrdctCompntLossValueOption value) {
        return new JAXBElement<PrdctCompntLossValueOption>(_PrdctCompntLossValueOption_QNAME, PrdctCompntLossValueOption.class, null, value);
    }

}
