//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.get_policy_contact_list_by_defined_role_inputs_crp30x1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.corporate.account_service_representativex1.AccountServiceRepresentative;
import ei.corporate.customer_service_representativex1.CustomerServiceRepresentative;
import ei.corporate.underwriter_assistantx1.UnderwriterAssistant;
import ei.corporate.underwriterx1.Underwriter;


/**
 * <p>Java class for GetPolicyContactListByDefinedRoleInputs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetPolicyContactListByDefinedRoleInputs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Underwriter" type="{http://ei/corporate/underwriterx1}Underwriter" minOccurs="0"/>
 *         &lt;element name="UnderwriterAssistant" type="{http://ei/corporate/underwriter_assistantx1}UnderwriterAssistant" minOccurs="0"/>
 *         &lt;element name="AccountServiceRepresentative" type="{http://ei/corporate/account_service_representativex1}AccountServiceRepresentative" minOccurs="0"/>
 *         &lt;element name="CustomerServiceRepresentative" type="{http://ei/corporate/customer_service_representativex1}CustomerServiceRepresentative" minOccurs="0"/>
 *         &lt;element name="PolicyNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PolicyTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PolicyTypeSubCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BranchNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsurerProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StrategicBusinessUnitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OfferingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MarketingProductGroupCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactTypeAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetPolicyContactListByDefinedRoleInputs", namespace = "http://ei/corporate/get_policy_contact_list_by_defined_role_inputs_crp30x1", propOrder = {
    "underwriter",
    "underwriterAssistant",
    "accountServiceRepresentative",
    "customerServiceRepresentative",
    "policyNumber",
    "policyTypeCode",
    "policyTypeSubCode",
    "branchNumber",
    "insurerProductCode",
    "strategicBusinessUnitCode",
    "offeringNumber",
    "marketingProductGroupCode",
    "contactTypeAbbreviation"
})
public class GetPolicyContactListByDefinedRoleInputs {

    @XmlElement(name = "Underwriter")
    protected Underwriter underwriter;
    @XmlElement(name = "UnderwriterAssistant")
    protected UnderwriterAssistant underwriterAssistant;
    @XmlElement(name = "AccountServiceRepresentative")
    protected AccountServiceRepresentative accountServiceRepresentative;
    @XmlElement(name = "CustomerServiceRepresentative")
    protected CustomerServiceRepresentative customerServiceRepresentative;
    @XmlElement(name = "PolicyNumber")
    protected String policyNumber;
    @XmlElement(name = "PolicyTypeCode")
    protected String policyTypeCode;
    @XmlElement(name = "PolicyTypeSubCode")
    protected String policyTypeSubCode;
    @XmlElement(name = "BranchNumber")
    protected String branchNumber;
    @XmlElement(name = "InsurerProductCode")
    protected String insurerProductCode;
    @XmlElement(name = "StrategicBusinessUnitCode")
    protected String strategicBusinessUnitCode;
    @XmlElement(name = "OfferingNumber")
    protected String offeringNumber;
    @XmlElement(name = "MarketingProductGroupCode")
    protected String marketingProductGroupCode;
    @XmlElement(name = "ContactTypeAbbreviation")
    protected List<String> contactTypeAbbreviation;

    /**
     * Gets the value of the underwriter property.
     * 
     * @return
     *     possible object is
     *     {@link Underwriter }
     *     
     */
    public Underwriter getUnderwriter() {
        return underwriter;
    }

    /**
     * Sets the value of the underwriter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Underwriter }
     *     
     */
    public void setUnderwriter(Underwriter value) {
        this.underwriter = value;
    }

    /**
     * Gets the value of the underwriterAssistant property.
     * 
     * @return
     *     possible object is
     *     {@link UnderwriterAssistant }
     *     
     */
    public UnderwriterAssistant getUnderwriterAssistant() {
        return underwriterAssistant;
    }

    /**
     * Sets the value of the underwriterAssistant property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderwriterAssistant }
     *     
     */
    public void setUnderwriterAssistant(UnderwriterAssistant value) {
        this.underwriterAssistant = value;
    }

    /**
     * Gets the value of the accountServiceRepresentative property.
     * 
     * @return
     *     possible object is
     *     {@link AccountServiceRepresentative }
     *     
     */
    public AccountServiceRepresentative getAccountServiceRepresentative() {
        return accountServiceRepresentative;
    }

    /**
     * Sets the value of the accountServiceRepresentative property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountServiceRepresentative }
     *     
     */
    public void setAccountServiceRepresentative(AccountServiceRepresentative value) {
        this.accountServiceRepresentative = value;
    }

    /**
     * Gets the value of the customerServiceRepresentative property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerServiceRepresentative }
     *     
     */
    public CustomerServiceRepresentative getCustomerServiceRepresentative() {
        return customerServiceRepresentative;
    }

    /**
     * Sets the value of the customerServiceRepresentative property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerServiceRepresentative }
     *     
     */
    public void setCustomerServiceRepresentative(CustomerServiceRepresentative value) {
        this.customerServiceRepresentative = value;
    }

    /**
     * Gets the value of the policyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNumber() {
        return policyNumber;
    }

    /**
     * Sets the value of the policyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNumber(String value) {
        this.policyNumber = value;
    }

    /**
     * Gets the value of the policyTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyTypeCode() {
        return policyTypeCode;
    }

    /**
     * Sets the value of the policyTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyTypeCode(String value) {
        this.policyTypeCode = value;
    }

    /**
     * Gets the value of the policyTypeSubCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyTypeSubCode() {
        return policyTypeSubCode;
    }

    /**
     * Sets the value of the policyTypeSubCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyTypeSubCode(String value) {
        this.policyTypeSubCode = value;
    }

    /**
     * Gets the value of the branchNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchNumber() {
        return branchNumber;
    }

    /**
     * Sets the value of the branchNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchNumber(String value) {
        this.branchNumber = value;
    }

    /**
     * Gets the value of the insurerProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurerProductCode() {
        return insurerProductCode;
    }

    /**
     * Sets the value of the insurerProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurerProductCode(String value) {
        this.insurerProductCode = value;
    }

    /**
     * Gets the value of the strategicBusinessUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategicBusinessUnitCode() {
        return strategicBusinessUnitCode;
    }

    /**
     * Sets the value of the strategicBusinessUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategicBusinessUnitCode(String value) {
        this.strategicBusinessUnitCode = value;
    }

    /**
     * Gets the value of the offeringNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferingNumber() {
        return offeringNumber;
    }

    /**
     * Sets the value of the offeringNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferingNumber(String value) {
        this.offeringNumber = value;
    }

    /**
     * Gets the value of the marketingProductGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketingProductGroupCode() {
        return marketingProductGroupCode;
    }

    /**
     * Sets the value of the marketingProductGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketingProductGroupCode(String value) {
        this.marketingProductGroupCode = value;
    }

    /**
     * Gets the value of the contactTypeAbbreviation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactTypeAbbreviation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactTypeAbbreviation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContactTypeAbbreviation() {
        if (contactTypeAbbreviation == null) {
            contactTypeAbbreviation = new ArrayList<String>();
        }
        return this.contactTypeAbbreviation;
    }

	@Override
	public String toString() {
		return "GetPolicyContactListByDefinedRoleInputs [underwriter="
				+ (this.getUnderwriter()!= null ? (this.getUnderwriter().toString()) : "") + ", underwriterAssistant="
				+ (this.getUnderwriterAssistant() !=null ? (this.getUnderwriterAssistant().toString()) : "" )+ ", accountServiceRepresentative="
				+ (this.getAccountServiceRepresentative() !=null ? (this.getAccountServiceRepresentative().toString()) : "")
				+ ", customerServiceRepresentative="
				+ (this.getCustomerServiceRepresentative()!= null ? (this.getCustomerServiceRepresentative().toString()) : "") + ", policyNumber="
				+ this.getPolicyNumber() + ", policyTypeCode=" + this.getPolicyTypeCode()
				+ ", policyTypeSubCode=" + this.getPolicyTypeSubCode()
				+ ", branchNumber=" + this.getBranchNumber() + ", insurerProductCode="
				+ this.getInsurerProductCode() + ", strategicBusinessUnitCode="
				+ this.getStrategicBusinessUnitCode() + ", offeringNumber="
				+ this.getOfferingNumber() + ", marketingProductGroupCode="
				+ this.getMarketingProductGroupCode() +  "]";
	}

}
