//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.producer.get_producer_with_commission_rates_reply_prd2x5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.producer.extended_producerx3.ExtendedProducer;


/**
 * <p>Java class for GetProducerWithCommissionRatesReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProducerWithCommissionRatesReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExtendedProducer" type="{http://ei/producer/extended_producerx3}ExtendedProducer" minOccurs="0"/>
 *         &lt;element name="ProducerFoundIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProducerWithCommissionRatesReply", namespace = "http://ei/producer/get_producer_with_commission_rates_reply_prd2X5", propOrder = {
    "extendedProducer",
    "producerFoundIndicator"
})
public class GetProducerWithCommissionRatesReply {

    @XmlElement(name = "ExtendedProducer")
    protected ExtendedProducer extendedProducer;
    @XmlElement(name = "ProducerFoundIndicator")
    protected Boolean producerFoundIndicator;

    /**
     * Gets the value of the extendedProducer property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedProducer }
     *     
     */
    public ExtendedProducer getExtendedProducer() {
        return extendedProducer;
    }

    /**
     * Sets the value of the extendedProducer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedProducer }
     *     
     */
    public void setExtendedProducer(ExtendedProducer value) {
        this.extendedProducer = value;
    }

    /**
     * Gets the value of the producerFoundIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProducerFoundIndicator() {
        return producerFoundIndicator;
    }

    /**
     * Sets the value of the producerFoundIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProducerFoundIndicator(Boolean value) {
        this.producerFoundIndicator = value;
    }

}
