//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.producer_commission_rate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.core.producer_commission_rate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProducerCommissionRate_QNAME = new QName("http://ei/core/producer_commission_rate", "ProducerCommissionRate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.core.producer_commission_rate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProducerCommissionRate }
     * 
     */
    public ProducerCommissionRate createProducerCommissionRate() {
        return new ProducerCommissionRate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProducerCommissionRate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/core/producer_commission_rate", name = "ProducerCommissionRate")
    public JAXBElement<ProducerCommissionRate> createProducerCommissionRate(ProducerCommissionRate value) {
        return new JAXBElement<ProducerCommissionRate>(_ProducerCommissionRate_QNAME, ProducerCommissionRate.class, null, value);
    }

}
