//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.production_office_informationx1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.branchx1.Branch;
import ei.producer.producerx4.Producer;


/**
 * <p>Java class for ProductionOfficeInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductionOfficeInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductionOffice" type="{http://ei/core/branchx1}Branch" minOccurs="0"/>
 *         &lt;element name="ProductionProducer" type="{http://ei/producer/producerx4}Producer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductionOfficeInformation", namespace = "http://ei/crm/production_office_informationx1", propOrder = {
    "productionOffice",
    "productionProducer"
})
public class ProductionOfficeInformation {

    @XmlElement(name = "ProductionOffice")
    protected Branch productionOffice;
    @XmlElement(name = "ProductionProducer")
    protected Producer productionProducer;

    /**
     * Gets the value of the productionOffice property.
     * 
     * @return
     *     possible object is
     *     {@link Branch }
     *     
     */
    public Branch getProductionOffice() {
        return productionOffice;
    }

    /**
     * Sets the value of the productionOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Branch }
     *     
     */
    public void setProductionOffice(Branch value) {
        this.productionOffice = value;
    }

    /**
     * Gets the value of the productionProducer property.
     * 
     * @return
     *     possible object is
     *     {@link Producer }
     *     
     */
    public Producer getProductionProducer() {
        return productionProducer;
    }

    /**
     * Sets the value of the productionProducer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Producer }
     *     
     */
    public void setProductionProducer(Producer value) {
        this.productionProducer = value;
    }

}
