//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.branch_retrieval_crp2x1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ei.corporate.get_producing_branch_list_request_crp2x1.GetProducingBranchListRequest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetProducingBranchListRequest" type="{http://ei/corporate/get_producing_branch_list_request_crp2x1}GetProducingBranchListRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getProducingBranchListRequest"
})
@XmlRootElement(name = "GetProducingBranchList")
public class GetProducingBranchList {

    @XmlElement(name = "GetProducingBranchListRequest", required = true, nillable = true)
    protected GetProducingBranchListRequest getProducingBranchListRequest;

    /**
     * Gets the value of the getProducingBranchListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetProducingBranchListRequest }
     *     
     */
    public GetProducingBranchListRequest getGetProducingBranchListRequest() {
        return getProducingBranchListRequest;
    }

    /**
     * Sets the value of the getProducingBranchListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetProducingBranchListRequest }
     *     
     */
    public void setGetProducingBranchListRequest(GetProducingBranchListRequest value) {
        this.getProducingBranchListRequest = value;
    }

}
