//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.commercial_insured_group_policy_retrieval_crm33x1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ei.crm.get_commercial_insured_group_policy_list_request_crm33x1.GetCommercialInsuredGroupPolicyListRequest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetCommercialInsuredGroupPolicyListRequest" type="{http://ei/crm/get_commercial_insured_group_policy_list_request_crm33x1}GetCommercialInsuredGroupPolicyListRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getCommercialInsuredGroupPolicyListRequest"
})
@XmlRootElement(name = "GetCommercialInsuredGroupPolicyList")
public class GetCommercialInsuredGroupPolicyList {

    @XmlElement(name = "GetCommercialInsuredGroupPolicyListRequest", required = true, nillable = true)
    protected GetCommercialInsuredGroupPolicyListRequest getCommercialInsuredGroupPolicyListRequest;

    /**
     * Gets the value of the getCommercialInsuredGroupPolicyListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetCommercialInsuredGroupPolicyListRequest }
     *     
     */
    public GetCommercialInsuredGroupPolicyListRequest getGetCommercialInsuredGroupPolicyListRequest() {
        return getCommercialInsuredGroupPolicyListRequest;
    }

    /**
     * Sets the value of the getCommercialInsuredGroupPolicyListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCommercialInsuredGroupPolicyListRequest }
     *     
     */
    public void setGetCommercialInsuredGroupPolicyListRequest(GetCommercialInsuredGroupPolicyListRequest value) {
        this.getCommercialInsuredGroupPolicyListRequest = value;
    }

}
