//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.get_commercial_insured_group_policy_list_request_crm33x1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.producer.producer_identifierx1.ProducerIdentifier;


/**
 * <p>Java class for GetCommercialInsuredGroupPolicyListRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCommercialInsuredGroupPolicyListRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProducerFilterIdentifier" type="{http://ei/producer/producer_identifierx1}ProducerIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SystemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceConsumerSystemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SyntheticTransactionTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdditionalOptionsText" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CommercialInsuredGroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WIPInsuredNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PolicyNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCommercialInsuredGroupPolicyListRequest", namespace = "http://ei/crm/get_commercial_insured_group_policy_list_request_crm33x1", propOrder = {
    "producerFilterIdentifier",
    "userId",
    "systemId",
    "serviceConsumerSystemId",
    "syntheticTransactionTypeCode",
    "additionalOptionsText",
    "commercialInsuredGroupId",
    "cpNumber",
    "wipInsuredNumber",
    "policyNumber",
    "userTypeDescription"
})
public class GetCommercialInsuredGroupPolicyListRequest {

    @XmlElement(name = "ProducerFilterIdentifier")
    protected List<ProducerIdentifier> producerFilterIdentifier;
    @XmlElement(name = "UserId")
    protected String userId;
    @XmlElement(name = "SystemId")
    protected String systemId;
    @XmlElement(name = "ServiceConsumerSystemId")
    protected String serviceConsumerSystemId;
    @XmlElement(name = "SyntheticTransactionTypeCode")
    protected String syntheticTransactionTypeCode;
    @XmlElement(name = "AdditionalOptionsText")
    protected List<String> additionalOptionsText;
    @XmlElement(name = "CommercialInsuredGroupId")
    protected String commercialInsuredGroupId;
    @XmlElement(name = "CPNumber")
    protected String cpNumber;
    @XmlElement(name = "WIPInsuredNumber")
    protected String wipInsuredNumber;
    @XmlElement(name = "PolicyNumber")
    protected String policyNumber;
    @XmlElement(name = "UserTypeDescription")
    protected String userTypeDescription;

    /**
     * Gets the value of the producerFilterIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the producerFilterIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProducerFilterIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProducerIdentifier }
     * 
     * 
     */
    public List<ProducerIdentifier> getProducerFilterIdentifier() {
        if (producerFilterIdentifier == null) {
            producerFilterIdentifier = new ArrayList<ProducerIdentifier>();
        }
        return this.producerFilterIdentifier;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the serviceConsumerSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceConsumerSystemId() {
        return serviceConsumerSystemId;
    }

    /**
     * Sets the value of the serviceConsumerSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceConsumerSystemId(String value) {
        this.serviceConsumerSystemId = value;
    }

    /**
     * Gets the value of the syntheticTransactionTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyntheticTransactionTypeCode() {
        return syntheticTransactionTypeCode;
    }

    /**
     * Sets the value of the syntheticTransactionTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyntheticTransactionTypeCode(String value) {
        this.syntheticTransactionTypeCode = value;
    }

    /**
     * Gets the value of the additionalOptionsText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalOptionsText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalOptionsText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdditionalOptionsText() {
        if (additionalOptionsText == null) {
            additionalOptionsText = new ArrayList<String>();
        }
        return this.additionalOptionsText;
    }

    /**
     * Gets the value of the commercialInsuredGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialInsuredGroupId() {
        return commercialInsuredGroupId;
    }

    /**
     * Sets the value of the commercialInsuredGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialInsuredGroupId(String value) {
        this.commercialInsuredGroupId = value;
    }

    /**
     * Gets the value of the cpNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPNumber() {
        return cpNumber;
    }

    /**
     * Sets the value of the cpNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPNumber(String value) {
        this.cpNumber = value;
    }

    /**
     * Gets the value of the wipInsuredNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWIPInsuredNumber() {
        return wipInsuredNumber;
    }

    /**
     * Sets the value of the wipInsuredNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWIPInsuredNumber(String value) {
        this.wipInsuredNumber = value;
    }

    /**
     * Gets the value of the policyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNumber() {
        return policyNumber;
    }

    /**
     * Sets the value of the policyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNumber(String value) {
        this.policyNumber = value;
    }

    /**
     * Gets the value of the userTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTypeDescription() {
        return userTypeDescription;
    }

    /**
     * Sets the value of the userTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTypeDescription(String value) {
        this.userTypeDescription = value;
    }

	@Override
	public String toString() {
		return "GetCommercialInsuredGroupPolicyListRequest [producerFilterIdentifier="
		
				+ (this.getProducerFilterIdentifier()!=null ? this.getProducerFilterIdentifier().toString() : null)
				+ ", userId="
				+ this.getUserId()
				+ ", systemId="
				+ this.getSystemId()
				+ ", serviceConsumerSystemId="
				+ this.getServiceConsumerSystemId()
				+ ", syntheticTransactionTypeCode="
				+ this.getSyntheticTransactionTypeCode()
				+ ", additionalOptionsText="
				+ this.getAdditionalOptionsText()
				+ ", commercialInsuredGroupId="
				+ this.getCommercialInsuredGroupId()
				+ ", cpNumber="
				+ this.getCPNumber()
				+ ", wipInsuredNumber="
				+ this.getWIPInsuredNumber()
				+ ", policyNumber="
				+ this.getPolicyNumber()
				+ ", userTypeDescription="
				+ this.getUserTypeDescription()
				+ "]";
	}

}
