//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.get_commercial_insured_group_policy_list_request_crm33x1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.crm.get_commercial_insured_group_policy_list_request_crm33x1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetCommercialInsuredGroupPolicyListRequest_QNAME = new QName("http://ei/crm/get_commercial_insured_group_policy_list_request_crm33x1", "GetCommercialInsuredGroupPolicyListRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.crm.get_commercial_insured_group_policy_list_request_crm33x1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCommercialInsuredGroupPolicyListRequest }
     * 
     */
    public GetCommercialInsuredGroupPolicyListRequest createGetCommercialInsuredGroupPolicyListRequest() {
        return new GetCommercialInsuredGroupPolicyListRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCommercialInsuredGroupPolicyListRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/crm/get_commercial_insured_group_policy_list_request_crm33x1", name = "GetCommercialInsuredGroupPolicyListRequest")
    public JAXBElement<GetCommercialInsuredGroupPolicyListRequest> createGetCommercialInsuredGroupPolicyListRequest(GetCommercialInsuredGroupPolicyListRequest value) {
        return new JAXBElement<GetCommercialInsuredGroupPolicyListRequest>(_GetCommercialInsuredGroupPolicyListRequest_QNAME, GetCommercialInsuredGroupPolicyListRequest.class, null, value);
    }

}
