//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ei/crm/get_commercial_insured_group_policy_list_request_crm33x1")
package ei.crm.get_commercial_insured_group_policy_list_request_crm33x1;
