//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.insuredx2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.addressx1.Address;
import ei.core.business_informationx2.BusinessInformation;


/**
 * <p>Java class for Insured complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Insured">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BusinessInformation" type="{http://ei/core/business_informationx2}BusinessInformation" minOccurs="0"/>
 *         &lt;element name="MailingAddress" type="{http://ei/core/addressx1}Address" minOccurs="0"/>
 *         &lt;element name="InsuredName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuredForeignName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuredAliasName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WIPInsuredNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuredTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuredRoleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuredRoleAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuredRoleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Insured", namespace = "http://ei/crm/insuredx2", propOrder = {
    "businessInformation",
    "mailingAddress",
    "insuredName",
    "insuredForeignName",
    "insuredAliasName",
    "cpNumber",
    "wipInsuredNumber",
    "insuredTypeCode",
    "insuredRoleName",
    "insuredRoleAbbreviation",
    "insuredRoleCode"
})
public class Insured {

    @XmlElement(name = "BusinessInformation")
    protected BusinessInformation businessInformation;
    @XmlElement(name = "MailingAddress")
    protected Address mailingAddress;
    @XmlElement(name = "InsuredName")
    protected String insuredName;
    @XmlElement(name = "InsuredForeignName")
    protected String insuredForeignName;
    @XmlElement(name = "InsuredAliasName")
    protected String insuredAliasName;
    @XmlElement(name = "CPNumber")
    protected String cpNumber;
    @XmlElement(name = "WIPInsuredNumber")
    protected String wipInsuredNumber;
    @XmlElement(name = "InsuredTypeCode")
    protected String insuredTypeCode;
    @XmlElement(name = "InsuredRoleName")
    protected String insuredRoleName;
    @XmlElement(name = "InsuredRoleAbbreviation")
    protected String insuredRoleAbbreviation;
    @XmlElement(name = "InsuredRoleCode")
    protected String insuredRoleCode;

    /**
     * Gets the value of the businessInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessInformation }
     *     
     */
    public BusinessInformation getBusinessInformation() {
        return businessInformation;
    }

    /**
     * Sets the value of the businessInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessInformation }
     *     
     */
    public void setBusinessInformation(BusinessInformation value) {
        this.businessInformation = value;
    }

    /**
     * Gets the value of the mailingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getMailingAddress() {
        return mailingAddress;
    }

    /**
     * Sets the value of the mailingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setMailingAddress(Address value) {
        this.mailingAddress = value;
    }

    /**
     * Gets the value of the insuredName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredName() {
        return insuredName;
    }

    /**
     * Sets the value of the insuredName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredName(String value) {
        this.insuredName = value;
    }

    /**
     * Gets the value of the insuredForeignName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredForeignName() {
        return insuredForeignName;
    }

    /**
     * Sets the value of the insuredForeignName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredForeignName(String value) {
        this.insuredForeignName = value;
    }

    /**
     * Gets the value of the insuredAliasName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredAliasName() {
        return insuredAliasName;
    }

    /**
     * Sets the value of the insuredAliasName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredAliasName(String value) {
        this.insuredAliasName = value;
    }

    /**
     * Gets the value of the cpNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPNumber() {
        return cpNumber;
    }

    /**
     * Sets the value of the cpNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPNumber(String value) {
        this.cpNumber = value;
    }

    /**
     * Gets the value of the wipInsuredNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWIPInsuredNumber() {
        return wipInsuredNumber;
    }

    /**
     * Sets the value of the wipInsuredNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWIPInsuredNumber(String value) {
        this.wipInsuredNumber = value;
    }

    /**
     * Gets the value of the insuredTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredTypeCode() {
        return insuredTypeCode;
    }

    /**
     * Sets the value of the insuredTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredTypeCode(String value) {
        this.insuredTypeCode = value;
    }

    /**
     * Gets the value of the insuredRoleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredRoleName() {
        return insuredRoleName;
    }

    /**
     * Sets the value of the insuredRoleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredRoleName(String value) {
        this.insuredRoleName = value;
    }

    /**
     * Gets the value of the insuredRoleAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredRoleAbbreviation() {
        return insuredRoleAbbreviation;
    }

    /**
     * Sets the value of the insuredRoleAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredRoleAbbreviation(String value) {
        this.insuredRoleAbbreviation = value;
    }

    /**
     * Gets the value of the insuredRoleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredRoleCode() {
        return insuredRoleCode;
    }

    /**
     * Sets the value of the insuredRoleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredRoleCode(String value) {
        this.insuredRoleCode = value;
    }
   
    @Override
	public String toString() {
		return "Insured [ InsuredName="
				+ this.getInsuredName()
				+ ", InsuredForeignName="
				+ this.getInsuredForeignName()
				+ ", InsuredAliasName="
				+ this.getInsuredAliasName()
				+ ", CPNumber="
				+ this.getCPNumber()
				+ ", WIPInsuredNumber="
				+ this.getWIPInsuredNumber()
				+ ", InsuredTypeCode="
				+ this.getInsuredTypeCode()
				+ ", InsuredRoleName="
				+ this.getInsuredRoleName()
				+ ", InsuredRoleAbbreviation="
				+ this.getInsuredRoleAbbreviation()
				+ ", InsuredRoleCode="
				+ this.getInsuredRoleCode()
				+ ", MailingAddress="
				+ (this.getMailingAddress() !=null ? this.getMailingAddress().toString() : null ) +"]";
	}
}
