//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.commercial_insured_group;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.crm.commercial_insured_group package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CommercialInsuredGroup_QNAME = new QName("http://ei/crm/commercial_insured_group", "CommercialInsuredGroup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.crm.commercial_insured_group
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommercialInsuredGroup }
     * 
     */
    public CommercialInsuredGroup createCommercialInsuredGroup() {
        return new CommercialInsuredGroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommercialInsuredGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/crm/commercial_insured_group", name = "CommercialInsuredGroup")
    public JAXBElement<CommercialInsuredGroup> createCommercialInsuredGroup(CommercialInsuredGroup value) {
        return new JAXBElement<CommercialInsuredGroup>(_CommercialInsuredGroup_QNAME, CommercialInsuredGroup.class, null, value);
    }

}
