//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.business_informationx3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * This business object contains classification and identification information about an organization doing business with Chubb.
 * 			
 * 
 * <p>Java class for BusinessInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SICCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NotForProfitIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MultinationalIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxPayerIdNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EnterpriseOwnershipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GovernmentOwnedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InitialYearWithChubb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EstablishedYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DFIAccountCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NAICSCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxExemptStatusIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublicOwnedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryStateOrProvinceAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryStateOrProvinceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryStateOrProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SICName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EnterpriseOwnershipName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessInformation", namespace = "http://ei/core/business_informationx3", propOrder = {
    "sicCode",
    "notForProfitIndicator",
    "multinationalIndicator",
    "taxPayerIdNumber",
    "enterpriseOwnershipCode",
    "governmentOwnedIndicator",
    "initialYearWithChubb",
    "establishedYear",
    "dfiAccountCode",
    "naicsCode",
    "taxExemptStatusIndicator",
    "publicOwnedIndicator",
    "primaryStateOrProvinceAbbreviation",
    "primaryStateOrProvinceName",
    "primaryStateOrProvinceCode",
    "sicName",
    "enterpriseOwnershipName"
})
public class BusinessInformation {

    @XmlElement(name = "SICCode")
    protected String sicCode;
    @XmlElement(name = "NotForProfitIndicator")
    protected String notForProfitIndicator;
    @XmlElement(name = "MultinationalIndicator")
    protected String multinationalIndicator;
    @XmlElement(name = "TaxPayerIdNumber")
    protected String taxPayerIdNumber;
    @XmlElement(name = "EnterpriseOwnershipCode")
    protected String enterpriseOwnershipCode;
    @XmlElement(name = "GovernmentOwnedIndicator")
    protected String governmentOwnedIndicator;
    @XmlElement(name = "InitialYearWithChubb")
    protected String initialYearWithChubb;
    @XmlElement(name = "EstablishedYear")
    protected String establishedYear;
    @XmlElement(name = "DFIAccountCode")
    protected String dfiAccountCode;
    @XmlElement(name = "NAICSCode")
    protected String naicsCode;
    @XmlElement(name = "TaxExemptStatusIndicator")
    protected String taxExemptStatusIndicator;
    @XmlElement(name = "PublicOwnedIndicator")
    protected String publicOwnedIndicator;
    @XmlElement(name = "PrimaryStateOrProvinceAbbreviation")
    protected String primaryStateOrProvinceAbbreviation;
    @XmlElement(name = "PrimaryStateOrProvinceName")
    protected String primaryStateOrProvinceName;
    @XmlElement(name = "PrimaryStateOrProvinceCode")
    protected String primaryStateOrProvinceCode;
    @XmlElement(name = "SICName")
    protected String sicName;
    @XmlElement(name = "EnterpriseOwnershipName")
    protected String enterpriseOwnershipName;

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the notForProfitIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotForProfitIndicator() {
        return notForProfitIndicator;
    }

    /**
     * Sets the value of the notForProfitIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotForProfitIndicator(String value) {
        this.notForProfitIndicator = value;
    }

    /**
     * Gets the value of the multinationalIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultinationalIndicator() {
        return multinationalIndicator;
    }

    /**
     * Sets the value of the multinationalIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultinationalIndicator(String value) {
        this.multinationalIndicator = value;
    }

    /**
     * Gets the value of the taxPayerIdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxPayerIdNumber() {
        return taxPayerIdNumber;
    }

    /**
     * Sets the value of the taxPayerIdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxPayerIdNumber(String value) {
        this.taxPayerIdNumber = value;
    }

    /**
     * Gets the value of the enterpriseOwnershipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseOwnershipCode() {
        return enterpriseOwnershipCode;
    }

    /**
     * Sets the value of the enterpriseOwnershipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseOwnershipCode(String value) {
        this.enterpriseOwnershipCode = value;
    }

    /**
     * Gets the value of the governmentOwnedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovernmentOwnedIndicator() {
        return governmentOwnedIndicator;
    }

    /**
     * Sets the value of the governmentOwnedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovernmentOwnedIndicator(String value) {
        this.governmentOwnedIndicator = value;
    }

    /**
     * Gets the value of the initialYearWithChubb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialYearWithChubb() {
        return initialYearWithChubb;
    }

    /**
     * Sets the value of the initialYearWithChubb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialYearWithChubb(String value) {
        this.initialYearWithChubb = value;
    }

    /**
     * Gets the value of the establishedYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstablishedYear() {
        return establishedYear;
    }

    /**
     * Sets the value of the establishedYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstablishedYear(String value) {
        this.establishedYear = value;
    }

    /**
     * Gets the value of the dfiAccountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFIAccountCode() {
        return dfiAccountCode;
    }

    /**
     * Sets the value of the dfiAccountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFIAccountCode(String value) {
        this.dfiAccountCode = value;
    }

    /**
     * Gets the value of the naicsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICSCode() {
        return naicsCode;
    }

    /**
     * Sets the value of the naicsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICSCode(String value) {
        this.naicsCode = value;
    }

    /**
     * Gets the value of the taxExemptStatusIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptStatusIndicator() {
        return taxExemptStatusIndicator;
    }

    /**
     * Sets the value of the taxExemptStatusIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptStatusIndicator(String value) {
        this.taxExemptStatusIndicator = value;
    }

    /**
     * Gets the value of the publicOwnedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicOwnedIndicator() {
        return publicOwnedIndicator;
    }

    /**
     * Sets the value of the publicOwnedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicOwnedIndicator(String value) {
        this.publicOwnedIndicator = value;
    }

    /**
     * Gets the value of the primaryStateOrProvinceAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryStateOrProvinceAbbreviation() {
        return primaryStateOrProvinceAbbreviation;
    }

    /**
     * Sets the value of the primaryStateOrProvinceAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryStateOrProvinceAbbreviation(String value) {
        this.primaryStateOrProvinceAbbreviation = value;
    }

    /**
     * Gets the value of the primaryStateOrProvinceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryStateOrProvinceName() {
        return primaryStateOrProvinceName;
    }

    /**
     * Sets the value of the primaryStateOrProvinceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryStateOrProvinceName(String value) {
        this.primaryStateOrProvinceName = value;
    }

    /**
     * Gets the value of the primaryStateOrProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryStateOrProvinceCode() {
        return primaryStateOrProvinceCode;
    }

    /**
     * Sets the value of the primaryStateOrProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryStateOrProvinceCode(String value) {
        this.primaryStateOrProvinceCode = value;
    }

    /**
     * Gets the value of the sicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICName() {
        return sicName;
    }

    /**
     * Sets the value of the sicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICName(String value) {
        this.sicName = value;
    }

    /**
     * Gets the value of the enterpriseOwnershipName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseOwnershipName() {
        return enterpriseOwnershipName;
    }

    /**
     * Sets the value of the enterpriseOwnershipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseOwnershipName(String value) {
        this.enterpriseOwnershipName = value;
    }

}
