//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package chubb_corporate.business.get_access_user_profile_management_ebe4x1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import chubb_corporate.business.get_access_user_profile_list_reply_ebe4x1.GetAccessUserProfileListReply;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetAccessUserProfileListReply" type="{http://chubb_corporate/business/get_access_user_profile_list_reply_ebe4x1}GetAccessUserProfileListReply"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getAccessUserProfileListReply"
})
@XmlRootElement(name = "GetAccessUserProfileListResponse")
public class GetAccessUserProfileListResponse
    implements Serializable
{

    @XmlElement(name = "GetAccessUserProfileListReply", required = true, nillable = true)
    protected GetAccessUserProfileListReply getAccessUserProfileListReply;

    /**
     * Gets the value of the getAccessUserProfileListReply property.
     * 
     * @return
     *     possible object is
     *     {@link GetAccessUserProfileListReply }
     *     
     */
    public GetAccessUserProfileListReply getGetAccessUserProfileListReply() {
        return getAccessUserProfileListReply;
    }

    /**
     * Sets the value of the getAccessUserProfileListReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAccessUserProfileListReply }
     *     
     */
    public void setGetAccessUserProfileListReply(GetAccessUserProfileListReply value) {
        this.getAccessUserProfileListReply = value;
    }

}
