<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/producer/producer_cross_reference_retrieval_prd6x1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/producer/producer_cross_reference_retrieval_prd6x1_http" name="ProducerCrossReferenceRetrievalPRD6X1Http" targetNamespace="http://ei/producer/producer_cross_reference_retrieval_prd6x1_http">
  <wsdl:import location="ProducerCrossReferenceRetrievalPRD6X1.wsdl" namespace="http://ei/producer/producer_cross_reference_retrieval_prd6x1" />
  <wsdl:binding name="ProducerCrossReferenceRetrievalPRD6X1HttpBinding" type="Port_0:ProducerCrossReferenceRetrievalPRD6X1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetProducerCrossReference">
      <soap:operation soapAction="GetProducerCrossReference" />
      <wsdl:input name="GetProducerCrossReferenceRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProducerCrossReferenceResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetFilteredProducerCrossRefList">
     <soap:operation soapAction="GetFilteredProducerCrossRefList" />
      <wsdl:input name="GetFilteredProducerCrossRefListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetFilteredProducerCrossRefListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
        <wsdl:operation name="GetProducerId">
     <soap:operation soapAction="GetProducerId" />
      <wsdl:input name="GetProducerIdRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProducerIdResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="ProducerCrossReferenceRetrievalPRD6X1HttpService">
    <wsdl:port binding="this:ProducerCrossReferenceRetrievalPRD6X1HttpBinding" name="ProducerCrossReferenceRetrievalPRD6X1HTTP_ProducerCrossReferenceRetrievalPRD6X1HttpPort">
      <soap:address location="Contact ICC for ProducerCrossReferenceRetrievalPRD6X1Http Endpoint" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>