<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/product/product_retrieval_pdt1x1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/product/product_retrieval_pdt1x1_http" name="ProductRetrievalPDT1X1Http" targetNamespace="http://ei/product/product_retrieval_pdt1x1_http">
  <wsdl:import location="ProductRetrievalPDT1X1.wsdl" namespace="http://ei/product/product_retrieval_pdt1x1" />
  <wsdl:binding name="ProductRetrievalPDT1X1HttpBinding" type="Port_0:ProductRetrievalPDT1X1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetProduct">
      <soap:operation soapAction="GetProduct" />
      <wsdl:input name="GetProductRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProductResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetFilteredProductList">
      <soap:operation soapAction="GetFilteredProductList" />
      <wsdl:input name="GetFilteredProductListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetFilteredProductListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetMarketingProductGroupList">
      <soap:operation soapAction="GetMarketingProductGroupList" />
      <wsdl:input name="GetMarketingProductGroupListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetMarketingProductGroupListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProductRetrievalPDT1X1HttpService">
    <wsdl:port binding="this:ProductRetrievalPDT1X1HttpBinding" name="ProductRetrievalPDT1X1HTTP_ProductRetrievalPDT1X1HttpPort">
      <soap:address location="http://EIPRDCTRETRVLPDT1X1-ut/ProductServicesWeb/sca/ProductRetrievalPDT1X1Http" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>