//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.reporting.commercial_policy_book_of_business_reporting_rpt3x1_http;

import javax.xml.ws.WebFault;
import ei.core.simplefault.SimpleFault;

@WebFault(name = "SimpleFaultReply", targetNamespace = "http://ei/reporting/commercial_policy_book_of_business_reporting_rpt3x1")
public class GenerateBookOfBusinessReportSimpleFaultReplyMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SimpleFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GenerateBookOfBusinessReportSimpleFaultReplyMsg(String message, SimpleFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public GenerateBookOfBusinessReportSimpleFaultReplyMsg(String message, SimpleFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ei.core.simplefault.SimpleFault
     */
    public SimpleFault getFaultInfo() {
        return faultInfo;
    }

}
