//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.prdct_compnt_exclusion_variation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.prdct_compnt_cross_reference.PrdctCompntCrossReference;
import ei.core.prdct_compnt_rule_group.PrdctCompntRuleGroup;
import ei.core.prdct_compnt_subject_type_part.PrdctCompntSubjectTypePart;


/**
 * <p>Java class for PrdctCompntExclusionVariation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrdctCompntExclusionVariation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductComponentRuleGroup" type="{http://ei/core/prdct_compnt_rule_group}PrdctCompntRuleGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubjectTypePart" type="{http://ei/core/prdct_compnt_subject_type_part}PrdctCompntSubjectTypePart" minOccurs="0"/>
 *         &lt;element name="ProductCrossReference" type="{http://ei/core/prdct_compnt_cross_reference}PrdctCompntCrossReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductComponentClassificationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductTypeClassificationDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductCatalogPCMPOMasterGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentDescriptionText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentGroupGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductComponentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TerrorismCoverageIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RepeatableComponentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateSpecificComponentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimsMadeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimsMadeStatisticalReportingCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProducerApplicationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductOfferingApplicationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WritingCompanyApplicationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrdctCompntExclusionVariation", namespace = "http://ei/core/prdct_compnt_exclusion_variation", propOrder = {
    "productComponentRuleGroup",
    "subjectTypePart",
    "productCrossReference",
    "productComponentClassificationCode",
    "productTypeClassificationDescription",
    "productCatalogPCMPOMasterGIN",
    "productComponentAbbreviation",
    "productComponentShortName",
    "productComponentName",
    "productComponentDescriptionText",
    "productComponentGroupGIN",
    "productComponentGroupName",
    "productComponentTypeCode",
    "terrorismCoverageIndicator",
    "repeatableComponentIndicator",
    "dateSpecificComponentIndicator",
    "claimsMadeIndicator",
    "claimsMadeStatisticalReportingCode",
    "producerApplicationIndicator",
    "productOfferingApplicationIndicator",
    "writingCompanyApplicationIndicator"
})
public class PrdctCompntExclusionVariation {

    @XmlElement(name = "ProductComponentRuleGroup")
    protected List<PrdctCompntRuleGroup> productComponentRuleGroup;
    @XmlElement(name = "SubjectTypePart")
    protected PrdctCompntSubjectTypePart subjectTypePart;
    @XmlElement(name = "ProductCrossReference")
    protected List<PrdctCompntCrossReference> productCrossReference;
    @XmlElement(name = "ProductComponentClassificationCode")
    protected String productComponentClassificationCode;
    @XmlElement(name = "ProductTypeClassificationDescription")
    protected String productTypeClassificationDescription;
    @XmlElement(name = "ProductCatalogPCMPOMasterGIN")
    protected String productCatalogPCMPOMasterGIN;
    @XmlElement(name = "ProductComponentAbbreviation")
    protected String productComponentAbbreviation;
    @XmlElement(name = "ProductComponentShortName")
    protected String productComponentShortName;
    @XmlElement(name = "ProductComponentName")
    protected String productComponentName;
    @XmlElement(name = "ProductComponentDescriptionText")
    protected String productComponentDescriptionText;
    @XmlElement(name = "ProductComponentGroupGIN")
    protected String productComponentGroupGIN;
    @XmlElement(name = "ProductComponentGroupName")
    protected String productComponentGroupName;
    @XmlElement(name = "ProductComponentTypeCode")
    protected String productComponentTypeCode;
    @XmlElement(name = "TerrorismCoverageIndicator")
    protected String terrorismCoverageIndicator;
    @XmlElement(name = "RepeatableComponentIndicator")
    protected String repeatableComponentIndicator;
    @XmlElement(name = "DateSpecificComponentIndicator")
    protected String dateSpecificComponentIndicator;
    @XmlElement(name = "ClaimsMadeIndicator")
    protected String claimsMadeIndicator;
    @XmlElement(name = "ClaimsMadeStatisticalReportingCode")
    protected String claimsMadeStatisticalReportingCode;
    @XmlElement(name = "ProducerApplicationIndicator")
    protected String producerApplicationIndicator;
    @XmlElement(name = "ProductOfferingApplicationIndicator")
    protected String productOfferingApplicationIndicator;
    @XmlElement(name = "WritingCompanyApplicationIndicator")
    protected String writingCompanyApplicationIndicator;

    /**
     * Gets the value of the productComponentRuleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productComponentRuleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductComponentRuleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrdctCompntRuleGroup }
     * 
     * 
     */
    public List<PrdctCompntRuleGroup> getProductComponentRuleGroup() {
        if (productComponentRuleGroup == null) {
            productComponentRuleGroup = new ArrayList<PrdctCompntRuleGroup>();
        }
        return this.productComponentRuleGroup;
    }

    /**
     * Gets the value of the subjectTypePart property.
     * 
     * @return
     *     possible object is
     *     {@link PrdctCompntSubjectTypePart }
     *     
     */
    public PrdctCompntSubjectTypePart getSubjectTypePart() {
        return subjectTypePart;
    }

    /**
     * Sets the value of the subjectTypePart property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrdctCompntSubjectTypePart }
     *     
     */
    public void setSubjectTypePart(PrdctCompntSubjectTypePart value) {
        this.subjectTypePart = value;
    }

    /**
     * Gets the value of the productCrossReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCrossReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCrossReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrdctCompntCrossReference }
     * 
     * 
     */
    public List<PrdctCompntCrossReference> getProductCrossReference() {
        if (productCrossReference == null) {
            productCrossReference = new ArrayList<PrdctCompntCrossReference>();
        }
        return this.productCrossReference;
    }

    /**
     * Gets the value of the productComponentClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentClassificationCode() {
        return productComponentClassificationCode;
    }

    /**
     * Sets the value of the productComponentClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentClassificationCode(String value) {
        this.productComponentClassificationCode = value;
    }

    /**
     * Gets the value of the productTypeClassificationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTypeClassificationDescription() {
        return productTypeClassificationDescription;
    }

    /**
     * Sets the value of the productTypeClassificationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTypeClassificationDescription(String value) {
        this.productTypeClassificationDescription = value;
    }

    /**
     * Gets the value of the productCatalogPCMPOMasterGIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCatalogPCMPOMasterGIN() {
        return productCatalogPCMPOMasterGIN;
    }

    /**
     * Sets the value of the productCatalogPCMPOMasterGIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCatalogPCMPOMasterGIN(String value) {
        this.productCatalogPCMPOMasterGIN = value;
    }

    /**
     * Gets the value of the productComponentAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentAbbreviation() {
        return productComponentAbbreviation;
    }

    /**
     * Sets the value of the productComponentAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentAbbreviation(String value) {
        this.productComponentAbbreviation = value;
    }

    /**
     * Gets the value of the productComponentShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentShortName() {
        return productComponentShortName;
    }

    /**
     * Sets the value of the productComponentShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentShortName(String value) {
        this.productComponentShortName = value;
    }

    /**
     * Gets the value of the productComponentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentName() {
        return productComponentName;
    }

    /**
     * Sets the value of the productComponentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentName(String value) {
        this.productComponentName = value;
    }

    /**
     * Gets the value of the productComponentDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentDescriptionText() {
        return productComponentDescriptionText;
    }

    /**
     * Sets the value of the productComponentDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentDescriptionText(String value) {
        this.productComponentDescriptionText = value;
    }

    /**
     * Gets the value of the productComponentGroupGIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentGroupGIN() {
        return productComponentGroupGIN;
    }

    /**
     * Sets the value of the productComponentGroupGIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentGroupGIN(String value) {
        this.productComponentGroupGIN = value;
    }

    /**
     * Gets the value of the productComponentGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentGroupName() {
        return productComponentGroupName;
    }

    /**
     * Sets the value of the productComponentGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentGroupName(String value) {
        this.productComponentGroupName = value;
    }

    /**
     * Gets the value of the productComponentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductComponentTypeCode() {
        return productComponentTypeCode;
    }

    /**
     * Sets the value of the productComponentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductComponentTypeCode(String value) {
        this.productComponentTypeCode = value;
    }

    /**
     * Gets the value of the terrorismCoverageIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerrorismCoverageIndicator() {
        return terrorismCoverageIndicator;
    }

    /**
     * Sets the value of the terrorismCoverageIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerrorismCoverageIndicator(String value) {
        this.terrorismCoverageIndicator = value;
    }

    /**
     * Gets the value of the repeatableComponentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepeatableComponentIndicator() {
        return repeatableComponentIndicator;
    }

    /**
     * Sets the value of the repeatableComponentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepeatableComponentIndicator(String value) {
        this.repeatableComponentIndicator = value;
    }

    /**
     * Gets the value of the dateSpecificComponentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateSpecificComponentIndicator() {
        return dateSpecificComponentIndicator;
    }

    /**
     * Sets the value of the dateSpecificComponentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateSpecificComponentIndicator(String value) {
        this.dateSpecificComponentIndicator = value;
    }

    /**
     * Gets the value of the claimsMadeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimsMadeIndicator() {
        return claimsMadeIndicator;
    }

    /**
     * Sets the value of the claimsMadeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimsMadeIndicator(String value) {
        this.claimsMadeIndicator = value;
    }

    /**
     * Gets the value of the claimsMadeStatisticalReportingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimsMadeStatisticalReportingCode() {
        return claimsMadeStatisticalReportingCode;
    }

    /**
     * Sets the value of the claimsMadeStatisticalReportingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimsMadeStatisticalReportingCode(String value) {
        this.claimsMadeStatisticalReportingCode = value;
    }

    /**
     * Gets the value of the producerApplicationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerApplicationIndicator() {
        return producerApplicationIndicator;
    }

    /**
     * Sets the value of the producerApplicationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerApplicationIndicator(String value) {
        this.producerApplicationIndicator = value;
    }

    /**
     * Gets the value of the productOfferingApplicationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductOfferingApplicationIndicator() {
        return productOfferingApplicationIndicator;
    }

    /**
     * Sets the value of the productOfferingApplicationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductOfferingApplicationIndicator(String value) {
        this.productOfferingApplicationIndicator = value;
    }

    /**
     * Gets the value of the writingCompanyApplicationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWritingCompanyApplicationIndicator() {
        return writingCompanyApplicationIndicator;
    }

    /**
     * Sets the value of the writingCompanyApplicationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWritingCompanyApplicationIndicator(String value) {
        this.writingCompanyApplicationIndicator = value;
    }

}
