//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.commercial_insured_group_policy_retrieval_crm33x1_http;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ei.crm.get_commercial_insured_group_policy_list_reply_crm33x1.GetCommercialInsuredGroupPolicyListReply;
import ei.crm.get_commercial_insured_group_policy_list_request_crm33x1.GetCommercialInsuredGroupPolicyListRequest;

@WebService(name = "CommercialInsuredGroupPolicyRetrievalCRM33X1", targetNamespace = "http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1")
@XmlSeeAlso({
    ei.producer.producer_enrollment_options.ObjectFactory.class,
    ei.core.status_informationx2.ObjectFactory.class,
    ei.producer.producer_identifierx1.ObjectFactory.class,
    ei.crm.commercial_insured_group_with_policy_term.ObjectFactory.class,
    ei.crm.production_office_informationx1.ObjectFactory.class,
    ei.crm.get_commercial_insured_group_policy_list_reply_crm33x1.ObjectFactory.class,
    ei.core.business_informationx3.ObjectFactory.class,
    ei.crm.insuredx5.ObjectFactory.class,
    ei.corporate.customer_service_representativex1.ObjectFactory.class,
    ei.core.commission_rates_by_policy_category.ObjectFactory.class,
    ei.core.addressx3.ObjectFactory.class,
    ei.corporate.underwriterx1.ObjectFactory.class,
    ei.core.departmentx1.ObjectFactory.class,
    ei.crm.policy_termx6.ObjectFactory.class,
    ei.crm.insured_with_policy_term.ObjectFactory.class,
    ei.core.insurance_admin_role.ObjectFactory.class,
    ei.core.individual_information.ObjectFactory.class,
    ei.core.typed_address.ObjectFactory.class,
    ei.core.simplefault.ObjectFactory.class,
    ei.crm.commercial_insured_group.ObjectFactory.class,
    ei.corporate.account_service_representativex1.ObjectFactory.class,
    ei.producer.producerx4.ObjectFactory.class,
    ei.corporate.underwriter_assistantx1.ObjectFactory.class,
    ei.core.customer_groupx2.ObjectFactory.class,
    ei.producer.producer_group.ObjectFactory.class,
    ei.crm.get_commercial_insured_group_policy_list_request_crm33x1.ObjectFactory.class,
    ei.core.resourcex1.ObjectFactory.class,
    ei.core.producer_commission_rate.ObjectFactory.class,
    ei.crm.commercial_insured_group_policy_retrieval_crm33x1.ObjectFactory.class,
    ei.core.insurerx1.ObjectFactory.class,
    ei.core.standardized_addressx3.ObjectFactory.class,
    ei.core.phone_information.ObjectFactory.class,
    ei.core.error_information.ObjectFactory.class,
    ei.core.email_information.ObjectFactory.class,
    ei.core.branchx1.ObjectFactory.class,
    ei.crm.coinsurancex1.ObjectFactory.class,
    ei.producer.producer_contact.ObjectFactory.class
})
public interface CommercialInsuredGroupPolicyRetrievalCRM33X1 {


    /**
     * 
     * @param getCommercialInsuredGroupPolicyListRequest
     * @return
     *     returns ei.crm.get_commercial_insured_group_policy_list_reply_crm33x1.GetCommercialInsuredGroupPolicyListReply
     * @throws GetCommercialInsuredGroupPolicyListSimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetCommercialInsuredGroupPolicyList", action = "GetCommercialInsuredGroupPolicyList")
    @WebResult(name = "GetCommercialInsuredGroupPolicyListReply", targetNamespace = "")
    @RequestWrapper(localName = "GetCommercialInsuredGroupPolicyList", targetNamespace = "http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1", className = "ei.crm.commercial_insured_group_policy_retrieval_crm33x1.GetCommercialInsuredGroupPolicyList")
    @ResponseWrapper(localName = "GetCommercialInsuredGroupPolicyListResponse", targetNamespace = "http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1", className = "ei.crm.commercial_insured_group_policy_retrieval_crm33x1.GetCommercialInsuredGroupPolicyListResponse")
    public GetCommercialInsuredGroupPolicyListReply getCommercialInsuredGroupPolicyList(
        @WebParam(name = "GetCommercialInsuredGroupPolicyListRequest", targetNamespace = "")
        GetCommercialInsuredGroupPolicyListRequest getCommercialInsuredGroupPolicyListRequest)
        throws GetCommercialInsuredGroupPolicyListSimpleFaultReplyMsg
    ;

}
