//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.name_search_by_all_names_request_crm4x4;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.crm.insuredx2.Insured;


/**
 * <p>Java class for NameSearchByAllNamesRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameSearchByAllNamesRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Insured" type="{http://ei/crm/insuredx2}Insured" minOccurs="0"/>
 *         &lt;element name="SystemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameSearchScoreThresholdNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="NameSearchLevelNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="NameSearchCurrentNameOnlyOverrideIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AdditionalOptionsText" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameSearchByAllNamesRequest", namespace = "http://ei/crm/name_search_by_all_names_request_crm4x4", propOrder = {
    "insured",
    "systemId",
    "userId",
    "nameSearchScoreThresholdNumber",
    "nameSearchLevelNumber",
    "nameSearchCurrentNameOnlyOverrideIndicator",
    "additionalOptionsText"
})
public class NameSearchByAllNamesRequest {

    @XmlElement(name = "Insured")
    protected Insured insured;
    @XmlElement(name = "SystemId")
    protected String systemId;
    @XmlElement(name = "UserId")
    protected String userId;
    @XmlElement(name = "NameSearchScoreThresholdNumber")
    protected BigInteger nameSearchScoreThresholdNumber;
    @XmlElement(name = "NameSearchLevelNumber")
    protected BigInteger nameSearchLevelNumber;
    @XmlElement(name = "NameSearchCurrentNameOnlyOverrideIndicator")
    protected Boolean nameSearchCurrentNameOnlyOverrideIndicator;
    @XmlElement(name = "AdditionalOptionsText")
    protected List<String> additionalOptionsText;

    /**
     * Gets the value of the insured property.
     * 
     * @return
     *     possible object is
     *     {@link Insured }
     *     
     */
    public Insured getInsured() {
        return insured;
    }

    /**
     * Sets the value of the insured property.
     * 
     * @param value
     *     allowed object is
     *     {@link Insured }
     *     
     */
    public void setInsured(Insured value) {
        this.insured = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the nameSearchScoreThresholdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNameSearchScoreThresholdNumber() {
        return nameSearchScoreThresholdNumber;
    }

    /**
     * Sets the value of the nameSearchScoreThresholdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNameSearchScoreThresholdNumber(BigInteger value) {
        this.nameSearchScoreThresholdNumber = value;
    }

    /**
     * Gets the value of the nameSearchLevelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNameSearchLevelNumber() {
        return nameSearchLevelNumber;
    }

    /**
     * Sets the value of the nameSearchLevelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNameSearchLevelNumber(BigInteger value) {
        this.nameSearchLevelNumber = value;
    }

    /**
     * Gets the value of the nameSearchCurrentNameOnlyOverrideIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNameSearchCurrentNameOnlyOverrideIndicator() {
        return nameSearchCurrentNameOnlyOverrideIndicator;
    }

    /**
     * Sets the value of the nameSearchCurrentNameOnlyOverrideIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNameSearchCurrentNameOnlyOverrideIndicator(Boolean value) {
        this.nameSearchCurrentNameOnlyOverrideIndicator = value;
    }

    /**
     * Gets the value of the additionalOptionsText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalOptionsText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalOptionsText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdditionalOptionsText() {
        if (additionalOptionsText == null) {
            additionalOptionsText = new ArrayList<String>();
        }
        return this.additionalOptionsText;
    }

}
