//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.get_default_contact_inputs_crp30x1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetDefaultContactInputs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetDefaultContactInputs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PolicyTypeSubCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BranchNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsurerProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StrategicBusinessUnitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MarketingProductGroupCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactTypeAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDefaultContactInputs", namespace = "http://ei/corporate/get_default_contact_inputs_crp30x1", propOrder = {
    "policyTypeCode",
    "policyTypeSubCode",
    "branchNumber",
    "insurerProductCode",
    "strategicBusinessUnitCode",
    "marketingProductGroupCode",
    "contactTypeAbbreviation"
})
public class GetDefaultContactInputs {

    @XmlElement(name = "PolicyTypeCode")
    protected String policyTypeCode;
    @XmlElement(name = "PolicyTypeSubCode")
    protected String policyTypeSubCode;
    @XmlElement(name = "BranchNumber")
    protected String branchNumber;
    @XmlElement(name = "InsurerProductCode")
    protected String insurerProductCode;
    @XmlElement(name = "StrategicBusinessUnitCode")
    protected String strategicBusinessUnitCode;
    @XmlElement(name = "MarketingProductGroupCode")
    protected String marketingProductGroupCode;
    @XmlElement(name = "ContactTypeAbbreviation")
    protected List<String> contactTypeAbbreviation;

    /**
     * Gets the value of the policyTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyTypeCode() {
        return policyTypeCode;
    }

    /**
     * Sets the value of the policyTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyTypeCode(String value) {
        this.policyTypeCode = value;
    }

    /**
     * Gets the value of the policyTypeSubCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyTypeSubCode() {
        return policyTypeSubCode;
    }

    /**
     * Sets the value of the policyTypeSubCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyTypeSubCode(String value) {
        this.policyTypeSubCode = value;
    }

    /**
     * Gets the value of the branchNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchNumber() {
        return branchNumber;
    }

    /**
     * Sets the value of the branchNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchNumber(String value) {
        this.branchNumber = value;
    }

    /**
     * Gets the value of the insurerProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurerProductCode() {
        return insurerProductCode;
    }

    /**
     * Sets the value of the insurerProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurerProductCode(String value) {
        this.insurerProductCode = value;
    }

    /**
     * Gets the value of the strategicBusinessUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategicBusinessUnitCode() {
        return strategicBusinessUnitCode;
    }

    /**
     * Sets the value of the strategicBusinessUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategicBusinessUnitCode(String value) {
        this.strategicBusinessUnitCode = value;
    }

    /**
     * Gets the value of the marketingProductGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketingProductGroupCode() {
        return marketingProductGroupCode;
    }

    /**
     * Sets the value of the marketingProductGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketingProductGroupCode(String value) {
        this.marketingProductGroupCode = value;
    }

    /**
     * Gets the value of the contactTypeAbbreviation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactTypeAbbreviation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactTypeAbbreviation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContactTypeAbbreviation() {
        if (contactTypeAbbreviation == null) {
            contactTypeAbbreviation = new ArrayList<String>();
        }
        return this.contactTypeAbbreviation;
    }

    @Override
	public String toString() {
		return "GetDefaultContactInputs [PolicyTypeCode="
				+ this.getPolicyTypeCode()
				+ ", PolicyTypeSubCode="
				+ this.getPolicyTypeSubCode()
				+ ", BranchNumber="
				+ this.getBranchNumber()
				+ ", InsurerProductCode="
				+ this.getInsurerProductCode()
				+ ", StrategicBusinessUnitCode="
				+ this.getStrategicBusinessUnitCode()
				+ ", MarketingProductGroupCode="
				+ this.getMarketingProductGroupCode() 
				+ "]";
	}
}
