//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.chubb.ecom.dgmk.ga.model;

import java.util.ArrayList;
import java.util.List;

/**
 * The Class StringArray is borrowed from the legacy GA web-service and being used by the GAUserProfileManagerImpl.
 */
public class StringArray {

    /** The string. */
    protected List<String> string;

    /**
     * Gets the string.
     *
     * @return the string
     */
    public List<String> getString() {
        if (string == null) {
            string = new ArrayList<String>();
        }
        return this.string;
    }

}
