//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package chubb_corporate.business.get_access_user_profile_management_ebe4x1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import chubb_corporate.get_access.simple_fault.SimpleFault;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the chubb_corporate.business.get_access_user_profile_management_ebe4x1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SimpleFaultReply_QNAME = new QName("http://chubb_corporate/business/get_access_user_profile_management_ebe4x1", "SimpleFaultReply");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: chubb_corporate.business.get_access_user_profile_management_ebe4x1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccessUserProfile }
     * 
     */
    public GetAccessUserProfile createGetAccessUserProfile() {
        return new GetAccessUserProfile();
    }

    /**
     * Create an instance of {@link UpdateGetAccessUserProfileResponse }
     * 
     */
    public UpdateGetAccessUserProfileResponse createUpdateGetAccessUserProfileResponse() {
        return new UpdateGetAccessUserProfileResponse();
    }

    /**
     * Create an instance of {@link AddGetAccessUserProfile }
     * 
     */
    public AddGetAccessUserProfile createAddGetAccessUserProfile() {
        return new AddGetAccessUserProfile();
    }

    /**
     * Create an instance of {@link GetAccessUserProfileList }
     * 
     */
    public GetAccessUserProfileList createGetAccessUserProfileList() {
        return new GetAccessUserProfileList();
    }

    /**
     * Create an instance of {@link UpdateGetAccessUserProfile }
     * 
     */
    public UpdateGetAccessUserProfile createUpdateGetAccessUserProfile() {
        return new UpdateGetAccessUserProfile();
    }

    /**
     * Create an instance of {@link ResetGetAccessUserPassword }
     * 
     */
    public ResetGetAccessUserPassword createResetGetAccessUserPassword() {
        return new ResetGetAccessUserPassword();
    }

    /**
     * Create an instance of {@link ChangeGetAccessUserProfileIdentifier }
     * 
     */
    public ChangeGetAccessUserProfileIdentifier createChangeGetAccessUserProfileIdentifier() {
        return new ChangeGetAccessUserProfileIdentifier();
    }

    /**
     * Create an instance of {@link ChangeGetAccessUserPassword }
     * 
     */
    public ChangeGetAccessUserPassword createChangeGetAccessUserPassword() {
        return new ChangeGetAccessUserPassword();
    }

    /**
     * Create an instance of {@link ChangeGetAccessUserPasswordResponse }
     * 
     */
    public ChangeGetAccessUserPasswordResponse createChangeGetAccessUserPasswordResponse() {
        return new ChangeGetAccessUserPasswordResponse();
    }

    /**
     * Create an instance of {@link AddGetAccessUserProfileResponse }
     * 
     */
    public AddGetAccessUserProfileResponse createAddGetAccessUserProfileResponse() {
        return new AddGetAccessUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetAccessUserProfileResponse }
     * 
     */
    public GetAccessUserProfileResponse createGetAccessUserProfileResponse() {
        return new GetAccessUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetAccessUserProfileListResponse }
     * 
     */
    public GetAccessUserProfileListResponse createGetAccessUserProfileListResponse() {
        return new GetAccessUserProfileListResponse();
    }

    /**
     * Create an instance of {@link ChangeGetAccessUserProfileIdentifierResponse }
     * 
     */
    public ChangeGetAccessUserProfileIdentifierResponse createChangeGetAccessUserProfileIdentifierResponse() {
        return new ChangeGetAccessUserProfileIdentifierResponse();
    }

    /**
     * Create an instance of {@link UpdateGetAccessUserProfileStatus }
     * 
     */
    public UpdateGetAccessUserProfileStatus createUpdateGetAccessUserProfileStatus() {
        return new UpdateGetAccessUserProfileStatus();
    }

    /**
     * Create an instance of {@link ResetGetAccessUserPasswordResponse }
     * 
     */
    public ResetGetAccessUserPasswordResponse createResetGetAccessUserPasswordResponse() {
        return new ResetGetAccessUserPasswordResponse();
    }

    /**
     * Create an instance of {@link UpdateGetAccessUserProfileStatusResponse }
     * 
     */
    public UpdateGetAccessUserProfileStatusResponse createUpdateGetAccessUserProfileStatusResponse() {
        return new UpdateGetAccessUserProfileStatusResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://chubb_corporate/business/get_access_user_profile_management_ebe4x1", name = "SimpleFaultReply")
    public JAXBElement<SimpleFault> createSimpleFaultReply(SimpleFault value) {
        return new JAXBElement<SimpleFault>(_SimpleFaultReply_QNAME, SimpleFault.class, null, value);
    }

}
