//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.prdct_compnt_subject_type_part;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrdctCompntSubjectTypePart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrdctCompntSubjectTypePart">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubjectTypePartGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubjectTypePartAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubjectTypePartClassificationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubjectTypePartName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubjectTypePartBusinessName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubjectTypePartDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrdctCompntSubjectTypePart", namespace = "http://ei/core/prdct_compnt_subject_type_part", propOrder = {
    "subjectTypePartGIN",
    "subjectTypePartAbbreviation",
    "subjectTypePartClassificationCode",
    "subjectTypePartName",
    "subjectTypePartBusinessName",
    "subjectTypePartDescription"
})
public class PrdctCompntSubjectTypePart {

    @XmlElement(name = "SubjectTypePartGIN")
    protected String subjectTypePartGIN;
    @XmlElement(name = "SubjectTypePartAbbreviation")
    protected String subjectTypePartAbbreviation;
    @XmlElement(name = "SubjectTypePartClassificationCode")
    protected String subjectTypePartClassificationCode;
    @XmlElement(name = "SubjectTypePartName")
    protected String subjectTypePartName;
    @XmlElement(name = "SubjectTypePartBusinessName")
    protected String subjectTypePartBusinessName;
    @XmlElement(name = "SubjectTypePartDescription")
    protected String subjectTypePartDescription;

    /**
     * Gets the value of the subjectTypePartGIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTypePartGIN() {
        return subjectTypePartGIN;
    }

    /**
     * Sets the value of the subjectTypePartGIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTypePartGIN(String value) {
        this.subjectTypePartGIN = value;
    }

    /**
     * Gets the value of the subjectTypePartAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTypePartAbbreviation() {
        return subjectTypePartAbbreviation;
    }

    /**
     * Sets the value of the subjectTypePartAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTypePartAbbreviation(String value) {
        this.subjectTypePartAbbreviation = value;
    }

    /**
     * Gets the value of the subjectTypePartClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTypePartClassificationCode() {
        return subjectTypePartClassificationCode;
    }

    /**
     * Sets the value of the subjectTypePartClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTypePartClassificationCode(String value) {
        this.subjectTypePartClassificationCode = value;
    }

    /**
     * Gets the value of the subjectTypePartName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTypePartName() {
        return subjectTypePartName;
    }

    /**
     * Sets the value of the subjectTypePartName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTypePartName(String value) {
        this.subjectTypePartName = value;
    }

    /**
     * Gets the value of the subjectTypePartBusinessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTypePartBusinessName() {
        return subjectTypePartBusinessName;
    }

    /**
     * Sets the value of the subjectTypePartBusinessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTypePartBusinessName(String value) {
        this.subjectTypePartBusinessName = value;
    }

    /**
     * Gets the value of the subjectTypePartDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTypePartDescription() {
        return subjectTypePartDescription;
    }

    /**
     * Sets the value of the subjectTypePartDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTypePartDescription(String value) {
        this.subjectTypePartDescription = value;
    }

}
