//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.language;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Language complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Language">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LanguageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LanguageGeographicalCoverageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DisplayLanguageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DisplayLanguageGeographicalCoverageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LanguageLocaleDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Language", namespace = "http://ei/core/language", propOrder = {
    "languageCode",
    "languageGeographicalCoverageCode",
    "displayLanguageCode",
    "displayLanguageGeographicalCoverageCode",
    "languageLocaleDescription"
})
public class Language {

    @XmlElement(name = "LanguageCode")
    protected String languageCode;
    @XmlElement(name = "LanguageGeographicalCoverageCode")
    protected String languageGeographicalCoverageCode;
    @XmlElement(name = "DisplayLanguageCode")
    protected String displayLanguageCode;
    @XmlElement(name = "DisplayLanguageGeographicalCoverageCode")
    protected String displayLanguageGeographicalCoverageCode;
    @XmlElement(name = "LanguageLocaleDescription")
    protected String languageLocaleDescription;

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the languageGeographicalCoverageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageGeographicalCoverageCode() {
        return languageGeographicalCoverageCode;
    }

    /**
     * Sets the value of the languageGeographicalCoverageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageGeographicalCoverageCode(String value) {
        this.languageGeographicalCoverageCode = value;
    }

    /**
     * Gets the value of the displayLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayLanguageCode() {
        return displayLanguageCode;
    }

    /**
     * Sets the value of the displayLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayLanguageCode(String value) {
        this.displayLanguageCode = value;
    }

    /**
     * Gets the value of the displayLanguageGeographicalCoverageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayLanguageGeographicalCoverageCode() {
        return displayLanguageGeographicalCoverageCode;
    }

    /**
     * Sets the value of the displayLanguageGeographicalCoverageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayLanguageGeographicalCoverageCode(String value) {
        this.displayLanguageGeographicalCoverageCode = value;
    }

    /**
     * Gets the value of the languageLocaleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageLocaleDescription() {
        return languageLocaleDescription;
    }

    /**
     * Sets the value of the languageLocaleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageLocaleDescription(String value) {
        this.languageLocaleDescription = value;
    }
    
   
    
    @Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("LanguageCode: " + this.getLanguageCode());
		sb.append(", LanguageGeographicalCoverageCode: " +this.getLanguageGeographicalCoverageCode());
		sb.append(", DisplayLanguageCode: " +this.getDisplayLanguageCode());
		sb.append(", DisplayLanguageGeographicalCoverageCode: " +this.getDisplayLanguageGeographicalCoverageCode());
		sb.append(", LanguageLocaleDescription: " +this.getLanguageLocaleDescription());
		return sb.toString();
	}
		

}
