//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.commercial_customer_search_crm4x4_http;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CommercialCustomerSearchCRM4X4HttpService", targetNamespace = "http://ei/crm/commercial_customer_search_crm4x4_http", wsdlLocation = "META-INF/wsdl/CommercialCustomerSearchCRM4X4Http.wsdl")
public class CommercialCustomerSearchCRM4X4HttpService
    extends Service
{

    private final static URL COMMERCIALCUSTOMERSEARCHCRM4X4HTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ei.crm.commercial_customer_search_crm4x4_http.CommercialCustomerSearchCRM4X4HttpService.class.getName());

    static {
        URL url = null;
        try {
            url = ei.crm.commercial_customer_search_crm4x4_http.CommercialCustomerSearchCRM4X4HttpService.class.getResource("/META-INF/wsdl/CommercialCustomerSearchCRM4X4Http.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/CommercialCustomerSearchCRM4X4Http.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/CommercialCustomerSearchCRM4X4Http.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMMERCIALCUSTOMERSEARCHCRM4X4HTTPSERVICE_WSDL_LOCATION = url;
    }

    public CommercialCustomerSearchCRM4X4HttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommercialCustomerSearchCRM4X4HttpService() {
        super(COMMERCIALCUSTOMERSEARCHCRM4X4HTTPSERVICE_WSDL_LOCATION, new QName("http://ei/crm/commercial_customer_search_crm4x4_http", "CommercialCustomerSearchCRM4X4HttpService"));
    }

    /**
     * 
     * @return
     *     returns CommercialCustomerSearchCRM4X4
     */
    @WebEndpoint(name = "CommercialCustomerSearchCRM4X4HTTP_CommercialCustomerSearchCRM4X4HttpPort")
    public CommercialCustomerSearchCRM4X4 getCommercialCustomerSearchCRM4X4HTTPCommercialCustomerSearchCRM4X4HttpPort() {
        return super.getPort(new QName("http://ei/crm/commercial_customer_search_crm4x4_http", "CommercialCustomerSearchCRM4X4HTTP_CommercialCustomerSearchCRM4X4HttpPort"), CommercialCustomerSearchCRM4X4.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommercialCustomerSearchCRM4X4
     */
    @WebEndpoint(name = "CommercialCustomerSearchCRM4X4HTTP_CommercialCustomerSearchCRM4X4HttpPort")
    public CommercialCustomerSearchCRM4X4 getCommercialCustomerSearchCRM4X4HTTPCommercialCustomerSearchCRM4X4HttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ei/crm/commercial_customer_search_crm4x4_http", "CommercialCustomerSearchCRM4X4HTTP_CommercialCustomerSearchCRM4X4HttpPort"), CommercialCustomerSearchCRM4X4.class, features);
    }

}
