//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.branch_retrieval_crp2x1_http;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ei.core.extendedbranch.ExtendedBranch;
import ei.corporate.get_branch_list_reply_crp2x1.GetBranchListReply;
import ei.corporate.get_branch_request_crp2x1.GetBranchRequest;
import ei.corporate.get_producing_branch_list_reply_crp2x1.GetProducingBranchListReply;
import ei.corporate.get_producing_branch_list_request_crp2x1.GetProducingBranchListRequest;
import ei.crp.get_local_language_branch_reply_crp2x1.GetLocalLanguageBranchReply;
import ei.crp.get_local_language_request_crp2x1.GetLocalLanguageBranchRequest;

@WebService(name = "BranchRetrievalCRP2X1", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1")
@XmlSeeAlso({
    ei.core.language.ObjectFactory.class,
    ei.crp.get_local_language_request_crp2x1.ObjectFactory.class,
    ei.corporate.get_producing_branch_list_request_crp2x1.ObjectFactory.class,
    ei.corporate.get_producing_branch_list_reply_crp2x1.ObjectFactory.class,
    ei.core.addressx1.ObjectFactory.class,
    ei.corporate.get_branch_list_reply_crp2x1.ObjectFactory.class,
    ei.crp.get_local_language_branch_reply_crp2x1.ObjectFactory.class,
    ei.core.simplefault.ObjectFactory.class,
    ei.core.branchx1.ObjectFactory.class,
    ei.corporate.get_branch_request_crp2x1.ObjectFactory.class,
    ei.corporate.branch_retrieval_crp2x1.ObjectFactory.class,
    ei.core.extendedbranch.ObjectFactory.class
})
public interface BranchRetrievalCRP2X1 {


    /**
     * 
     * @param getBranchRequest
     * @return
     *     returns ei.core.extendedbranch.ExtendedBranch
     * @throws GetBranchSimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetBranch", action = "GetBranch")
    @WebResult(name = "ExtendedBranch", targetNamespace = "")
    @RequestWrapper(localName = "GetBranch", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetBranch")
    @ResponseWrapper(localName = "GetBranchResponse", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetBranchResponse")
    public ExtendedBranch getBranch(
        @WebParam(name = "GetBranchRequest", targetNamespace = "")
        GetBranchRequest getBranchRequest)
        throws GetBranchSimpleFaultReplyMsg
    ;

    /**
     * 
     * @param asOfDate
     * @return
     *     returns ei.corporate.get_branch_list_reply_crp2x1.GetBranchListReply
     * @throws GetBranchListSimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetBranchList", action = "GetBranchList")
    @WebResult(name = "GetBranchListReply", targetNamespace = "")
    @RequestWrapper(localName = "GetBranchList", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetBranchList")
    @ResponseWrapper(localName = "GetBranchListResponse", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetBranchListResponse")
    public GetBranchListReply getBranchList(
        @WebParam(name = "AsOfDate", targetNamespace = "")
        XMLGregorianCalendar asOfDate)
        throws GetBranchListSimpleFaultReplyMsg
    ;

    /**
     * 
     * @param getLocalLanguageBranchRequest
     * @return
     *     returns ei.crp.get_local_language_branch_reply_crp2x1.GetLocalLanguageBranchReply
     * @throws GetLocalLanguageBranchSimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetLocalLanguageBranch", action = "GetLocalLanguageBranch")
    @WebResult(name = "GetLocalLanguageBranchReply", targetNamespace = "")
    @RequestWrapper(localName = "GetLocalLanguageBranch", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetLocalLanguageBranch")
    @ResponseWrapper(localName = "GetLocalLanguageBranchResponse", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetLocalLanguageBranchResponse")
    public GetLocalLanguageBranchReply getLocalLanguageBranch(
        @WebParam(name = "GetLocalLanguageBranchRequest", targetNamespace = "")
        GetLocalLanguageBranchRequest getLocalLanguageBranchRequest)
        throws GetLocalLanguageBranchSimpleFaultReplyMsg
    ;

    /**
     * 
     * @param getProducingBranchListRequest
     * @return
     *     returns ei.corporate.get_producing_branch_list_reply_crp2x1.GetProducingBranchListReply
     * @throws GetProducingBranchListSimpleFaultReplyMsg
     */
    @WebMethod(operationName = "GetProducingBranchList", action = "GetProducingBranchList")
    @WebResult(name = "GetProducingBranchListReply", targetNamespace = "")
    @RequestWrapper(localName = "GetProducingBranchList", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetProducingBranchList")
    @ResponseWrapper(localName = "GetProducingBranchListResponse", targetNamespace = "http://ei/corporate/branch_retrieval_crp2X1", className = "ei.corporate.branch_retrieval_crp2x1.GetProducingBranchListResponse")
    public GetProducingBranchListReply getProducingBranchList(
        @WebParam(name = "GetProducingBranchListRequest", targetNamespace = "")
        GetProducingBranchListRequest getProducingBranchListRequest)
        throws GetProducingBranchListSimpleFaultReplyMsg
    ;

}
