//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.producer.producer_retrieval_prd2x5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ei.producer.get_producer_list_request_prd2x5.GetProducerListRequest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetProducerListRequest" type="{http://ei/producer/get_producer_list_request_prd2x5}GetProducerListRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getProducerListRequest"
})
@XmlRootElement(name = "GetProducerList2X5")
public class GetProducerList2X5 {

    @XmlElement(name = "GetProducerListRequest", required = true, nillable = true)
    protected GetProducerListRequest getProducerListRequest;

    /**
     * Gets the value of the getProducerListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetProducerListRequest }
     *     
     */
    public GetProducerListRequest getGetProducerListRequest() {
        return getProducerListRequest;
    }

    /**
     * Sets the value of the getProducerListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetProducerListRequest }
     *     
     */
    public void setGetProducerListRequest(GetProducerListRequest value) {
        this.getProducerListRequest = value;
    }

}
