//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.producer.producer_retrieval_prd2x5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ei.core.simplefault.SimpleFault;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.producer.producer_retrieval_prd2x5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SimpleFaultReply_QNAME = new QName("http://ei/producer/producer_retrieval_prd2x5", "SimpleFaultReply");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.producer.producer_retrieval_prd2x5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProducerWithCommissionRates2X5 }
     * 
     */
    public GetProducerWithCommissionRates2X5 createGetProducerWithCommissionRates2X5() {
        return new GetProducerWithCommissionRates2X5();
    }

    /**
     * Create an instance of {@link GetProducerList2X5 }
     * 
     */
    public GetProducerList2X5 createGetProducerList2X5() {
        return new GetProducerList2X5();
    }

    /**
     * Create an instance of {@link GetFilteredProducerList2X5 }
     * 
     */
    public GetFilteredProducerList2X5 createGetFilteredProducerList2X5() {
        return new GetFilteredProducerList2X5();
    }

    /**
     * Create an instance of {@link GetProducer2X5 }
     * 
     */
    public GetProducer2X5 createGetProducer2X5() {
        return new GetProducer2X5();
    }

    /**
     * Create an instance of {@link GetFilteredProducerList2X5Response }
     * 
     */
    public GetFilteredProducerList2X5Response createGetFilteredProducerList2X5Response() {
        return new GetFilteredProducerList2X5Response();
    }

    /**
     * Create an instance of {@link GetProducerWithCommissionRates2X5Response }
     * 
     */
    public GetProducerWithCommissionRates2X5Response createGetProducerWithCommissionRates2X5Response() {
        return new GetProducerWithCommissionRates2X5Response();
    }

    /**
     * Create an instance of {@link GetProducer2X5Response }
     * 
     */
    public GetProducer2X5Response createGetProducer2X5Response() {
        return new GetProducer2X5Response();
    }

    /**
     * Create an instance of {@link GetProducerList2X5Response }
     * 
     */
    public GetProducerList2X5Response createGetProducerList2X5Response() {
        return new GetProducerList2X5Response();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/producer/producer_retrieval_prd2x5", name = "SimpleFaultReply")
    public JAXBElement<SimpleFault> createSimpleFaultReply(SimpleFault value) {
        return new JAXBElement<SimpleFault>(_SimpleFaultReply_QNAME, SimpleFault.class, null, value);
    }

}
