//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://chubb_corporate/get_access/source_system_user_profile_id")
package chubb_corporate.get_access.source_system_user_profile_id;
