//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.name_search_request_crm4x4;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.producer_identifierx2.ProducerIdentifier;
import ei.crm.insuredx2.Insured;


/**
 * <p>Java class for NameSearchRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameSearchRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Insured" type="{http://ei/crm/insuredx2}Insured" minOccurs="0"/>
 *         &lt;element name="ProducerFilterIdentifier" type="{http://ei/core/producer_identifierx2}ProducerIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SystemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceConsumerSystemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameSearchScoreThresholdNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="NameSearchLevelNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="NameSearchCurrentNameOnlyOverrideIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UserTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdditionalOptionsText" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameSearchRequest", namespace = "http://ei/crm/name_search_request_crm4x4", propOrder = {
    "insured",
    "producerFilterIdentifier",
    "systemId",
    "userId",
    "serviceConsumerSystemId",
    "nameSearchScoreThresholdNumber",
    "nameSearchLevelNumber",
    "nameSearchCurrentNameOnlyOverrideIndicator",
    "userTypeDescription",
    "additionalOptionsText"
})
public class NameSearchRequest {

    @XmlElement(name = "Insured")
    protected Insured insured;
    @XmlElement(name = "ProducerFilterIdentifier")
    protected List<ProducerIdentifier> producerFilterIdentifier;
    @XmlElement(name = "SystemId")
    protected String systemId;
    @XmlElement(name = "UserId")
    protected String userId;
    @XmlElement(name = "ServiceConsumerSystemId")
    protected String serviceConsumerSystemId;
    @XmlElement(name = "NameSearchScoreThresholdNumber")
    protected BigInteger nameSearchScoreThresholdNumber;
    @XmlElement(name = "NameSearchLevelNumber")
    protected BigInteger nameSearchLevelNumber;
    @XmlElement(name = "NameSearchCurrentNameOnlyOverrideIndicator")
    protected Boolean nameSearchCurrentNameOnlyOverrideIndicator;
    @XmlElement(name = "UserTypeDescription")
    protected String userTypeDescription;
    @XmlElement(name = "AdditionalOptionsText")
    protected List<String> additionalOptionsText;

    /**
     * Gets the value of the insured property.
     * 
     * @return
     *     possible object is
     *     {@link Insured }
     *     
     */
    public Insured getInsured() {
        return insured;
    }

    /**
     * Sets the value of the insured property.
     * 
     * @param value
     *     allowed object is
     *     {@link Insured }
     *     
     */
    public void setInsured(Insured value) {
        this.insured = value;
    }

    /**
     * Gets the value of the producerFilterIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the producerFilterIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProducerFilterIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProducerIdentifier }
     * 
     * 
     */
    public List<ProducerIdentifier> getProducerFilterIdentifier() {
        if (producerFilterIdentifier == null) {
            producerFilterIdentifier = new ArrayList<ProducerIdentifier>();
        }
        return this.producerFilterIdentifier;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the serviceConsumerSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceConsumerSystemId() {
        return serviceConsumerSystemId;
    }

    /**
     * Sets the value of the serviceConsumerSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceConsumerSystemId(String value) {
        this.serviceConsumerSystemId = value;
    }

    /**
     * Gets the value of the nameSearchScoreThresholdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNameSearchScoreThresholdNumber() {
        return nameSearchScoreThresholdNumber;
    }

    /**
     * Sets the value of the nameSearchScoreThresholdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNameSearchScoreThresholdNumber(BigInteger value) {
        this.nameSearchScoreThresholdNumber = value;
    }

    /**
     * Gets the value of the nameSearchLevelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNameSearchLevelNumber() {
        return nameSearchLevelNumber;
    }

    /**
     * Sets the value of the nameSearchLevelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNameSearchLevelNumber(BigInteger value) {
        this.nameSearchLevelNumber = value;
    }

    /**
     * Gets the value of the nameSearchCurrentNameOnlyOverrideIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNameSearchCurrentNameOnlyOverrideIndicator() {
        return nameSearchCurrentNameOnlyOverrideIndicator;
    }

    /**
     * Sets the value of the nameSearchCurrentNameOnlyOverrideIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNameSearchCurrentNameOnlyOverrideIndicator(Boolean value) {
        this.nameSearchCurrentNameOnlyOverrideIndicator = value;
    }

    /**
     * Gets the value of the userTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTypeDescription() {
        return userTypeDescription;
    }

    /**
     * Sets the value of the userTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTypeDescription(String value) {
        this.userTypeDescription = value;
    }

    /**
     * Gets the value of the additionalOptionsText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalOptionsText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalOptionsText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdditionalOptionsText() {
        if (additionalOptionsText == null) {
            additionalOptionsText = new ArrayList<String>();
        }
        return this.additionalOptionsText;
    }

    @Override
	public String toString() {
		return "NameSearchRequest [producerFilterIdentifier=" +
			
				(this.getProducerFilterIdentifier()!=null ? this.getProducerFilterIdentifier().toString() : null)
				
				+ ", Insured="
				+(this.getInsured()!=null ? this.getInsured().toString() : null)
				+ ", SystemId="
				+ this.getSystemId()
				+ ", UserID="
				+ this.getUserId()
				+ ", serviceConsumerSystemId="
				+ this.getServiceConsumerSystemId()
				+ ", NameSearchScoreThresholdNumber="
				+ this.getNameSearchScoreThresholdNumber()
				+ ", NameSearchLevelNumber="
				+ this.getNameSearchLevelNumber() 
				+ ", NameSearchCurrentNameOnlyOverrideIndicator="
				+ this.isNameSearchCurrentNameOnlyOverrideIndicator()
				+", UserTypeDescription="
				+ this.getUserTypeDescription()
				+", AdditionalOptionsText="
				+this.getAdditionalOptionsText()+ "]";
	}

}
