//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.contact_retrieval_crp30x1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ei.corporate.get_policy_contact_list_request_crp30x1.GetPolicyContactListRequest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetPolicyContactListRequest" type="{http://ei/corporate/get_policy_contact_list_request_crp30x1}GetPolicyContactListRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getPolicyContactListRequest"
})
@XmlRootElement(name = "GetPolicyContactList")
public class GetPolicyContactList {

    @XmlElement(name = "GetPolicyContactListRequest", required = true, nillable = true)
    protected GetPolicyContactListRequest getPolicyContactListRequest;

    /**
     * Gets the value of the getPolicyContactListRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetPolicyContactListRequest }
     *     
     */
    public GetPolicyContactListRequest getGetPolicyContactListRequest() {
        return getPolicyContactListRequest;
    }

    /**
     * Sets the value of the getPolicyContactListRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPolicyContactListRequest }
     *     
     */
    public void setGetPolicyContactListRequest(GetPolicyContactListRequest value) {
        this.getPolicyContactListRequest = value;
    }

}
