//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.contact_retrieval_crp30x1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ei.corporate.get_policy_contact_list_by_defined_role_request_crp30x1.GetPolicyContactListByDefinedRoleRequest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetPolicyContactListByDefinedRoleRequest" type="{http://ei/corporate/get_policy_contact_list_by_defined_role_request_crp30x1}GetPolicyContactListByDefinedRoleRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getPolicyContactListByDefinedRoleRequest"
})
@XmlRootElement(name = "GetPolicyContactListByDefinedRole")
public class GetPolicyContactListByDefinedRole {

    @XmlElement(name = "GetPolicyContactListByDefinedRoleRequest", required = true, nillable = true)
    protected GetPolicyContactListByDefinedRoleRequest getPolicyContactListByDefinedRoleRequest;

    /**
     * Gets the value of the getPolicyContactListByDefinedRoleRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetPolicyContactListByDefinedRoleRequest }
     *     
     */
    public GetPolicyContactListByDefinedRoleRequest getGetPolicyContactListByDefinedRoleRequest() {
        return getPolicyContactListByDefinedRoleRequest;
    }

    /**
     * Sets the value of the getPolicyContactListByDefinedRoleRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPolicyContactListByDefinedRoleRequest }
     *     
     */
    public void setGetPolicyContactListByDefinedRoleRequest(GetPolicyContactListByDefinedRoleRequest value) {
        this.getPolicyContactListByDefinedRoleRequest = value;
    }

}
