//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.underwriter_assistantx1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.corporate.underwriter_assistantx1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnderwriterAssistant_QNAME = new QName("http://ei/corporate/underwriter_assistantx1", "UnderwriterAssistant");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.corporate.underwriter_assistantx1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UnderwriterAssistant }
     * 
     */
    public UnderwriterAssistant createUnderwriterAssistant() {
        return new UnderwriterAssistant();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnderwriterAssistant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/corporate/underwriter_assistantx1", name = "UnderwriterAssistant")
    public JAXBElement<UnderwriterAssistant> createUnderwriterAssistant(UnderwriterAssistant value) {
        return new JAXBElement<UnderwriterAssistant>(_UnderwriterAssistant_QNAME, UnderwriterAssistant.class, null, value);
    }

}
