//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.get_country_request_crp10x1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.corporate.get_country_request_crp10x1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetCountryRequest_QNAME = new QName("http://ei/corporate/get_country_request_crp10x1", "GetCountryRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.corporate.get_country_request_crp10x1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCountryRequest }
     * 
     */
    public GetCountryRequest createGetCountryRequest() {
        return new GetCountryRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCountryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/corporate/get_country_request_crp10x1", name = "GetCountryRequest")
    public JAXBElement<GetCountryRequest> createGetCountryRequest(GetCountryRequest value) {
        return new JAXBElement<GetCountryRequest>(_GetCountryRequest_QNAME, GetCountryRequest.class, null, value);
    }

}
