//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.corporate.account_service_representativex1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.resourcex1.Resource;


/**
 * <p>Java class for AccountServiceRepresentative complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountServiceRepresentative">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ei/core/resourcex1}Resource">
 *       &lt;sequence>
 *         &lt;element name="ASRInitials" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountServiceRepresentative", namespace = "http://ei/corporate/account_service_representativex1", propOrder = {
    "asrInitials"
})
public class AccountServiceRepresentative
    extends Resource
{

    @XmlElement(name = "ASRInitials")
    protected String asrInitials;

    /**
     * Gets the value of the asrInitials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASRInitials() {
        return asrInitials;
    }

    /**
     * Sets the value of the asrInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASRInitials(String value) {
        this.asrInitials = value;
    }
    @Override
	public String toString() {
		return "AccountServiceRepresentative [ ASRInitials="
				+ this.getASRInitials()
				+ ", CP Number ="
				+ this.getCPNumber()
				+ "]";
	}
}
