<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/corporate/branch_retrieval_crp2X1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/corporate/branch_retrieval_crp2X1_http" name="BranchRetrievalCRP2X1Http" targetNamespace="http://ei/corporate/branch_retrieval_crp2X1_http">
  <wsdl:import location="BranchRetrievalCRP2X1.wsdl" namespace="http://ei/corporate/branch_retrieval_crp2X1" />
  <wsdl:binding name="BranchRetrievalCRP2X1HttpBinding" type="Port_0:BranchRetrievalCRP2X1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetBranch">
      <soap:operation soapAction="GetBranch" />
      <wsdl:input name="GetBranchRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetBranchResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetBranchList">
      <soap:operation soapAction="GetBranchList" />
      <wsdl:input name="GetBranchListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetBranchListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetLocalLanguageBranch">
      <soap:operation soapAction="GetLocalLanguageBranch" />
      <wsdl:input name="GetLocalLanguageBranchRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetLocalLanguageBranchResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
      <wsdl:operation name="GetProducingBranchList">
      <soap:operation soapAction="GetProducingBranchList" />
      <wsdl:input name="GetProducingBranchListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetProducingBranchListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BranchRetrievalCRP2X1HttpService">
    <wsdl:port binding="this:BranchRetrievalCRP2X1HttpBinding" name="BranchRetrievalCRP2X1HTTP_BranchRetrievalCRP2X1HttpPort">
      <soap:address location="http://EIBRRETCRP2X1D/Corporate2ServicesWeb/sca/BranchRetrievalCRP2X1Http" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>