<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1_http" name="CommercialInsuredGroupPolicyRetrievalCRM33X1Http" targetNamespace="http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1_http">
  <wsdl:import location="CommercialInsuredGroupPolicyRetrievalCRM33X1.wsdl" namespace="http://ei/crm/commercial_insured_group_policy_retrieval_crm33x1" />
  <wsdl:binding name="CommercialInsuredGroupPolicyRetrievalCRM33X1HttpBinding" type="Port_0:CommercialInsuredGroupPolicyRetrievalCRM33X1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetCommercialInsuredGroupPolicyList">
      <soap:operation soapAction="GetCommercialInsuredGroupPolicyList" />
      <wsdl:input name="GetCommercialInsuredGroupPolicyListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetCommercialInsuredGroupPolicyListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CommercialInsuredGroupPolicyRetrievalCRM33X1HttpService">
    <wsdl:port binding="this:CommercialInsuredGroupPolicyRetrievalCRM33X1HttpBinding" name="CommercialInsuredGroupPolicyRetrievalCRM33X1HTTP_CommercialInsuredGroupPolicyRetrievalCRM33X1HttpPort">
      <soap:address location="http://eicomlinsdgrppolrtrvlcrm33x1-ut/CRM6ServicesWeb/sca/CommercialInsuredGroupPolicyRetrievalCRM33X1Http" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>