//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.email_information;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmailInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmailInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceSystemEmailId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreferredEmailIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContactOrderPreferenceTypeNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="UsageTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactModePreferenceTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailInformation", namespace = "http://ei/core/email_information", propOrder = {
    "sourceSystemEmailId",
    "emailAddress",
    "emailTypeName",
    "emailTypeDescription",
    "preferredEmailIndicator",
    "contactOrderPreferenceTypeNumber",
    "usageTypeName",
    "contactModePreferenceTypeName"
})
public class EmailInformation {

    @XmlElement(name = "SourceSystemEmailId")
    protected String sourceSystemEmailId;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "EmailTypeName")
    protected String emailTypeName;
    @XmlElement(name = "EmailTypeDescription")
    protected String emailTypeDescription;
    @XmlElement(name = "PreferredEmailIndicator")
    protected Boolean preferredEmailIndicator;
    @XmlElement(name = "ContactOrderPreferenceTypeNumber")
    protected BigInteger contactOrderPreferenceTypeNumber;
    @XmlElement(name = "UsageTypeName")
    protected String usageTypeName;
    @XmlElement(name = "ContactModePreferenceTypeName")
    protected String contactModePreferenceTypeName;

    /**
     * Gets the value of the sourceSystemEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemEmailId() {
        return sourceSystemEmailId;
    }

    /**
     * Sets the value of the sourceSystemEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemEmailId(String value) {
        this.sourceSystemEmailId = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the emailTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailTypeName() {
        return emailTypeName;
    }

    /**
     * Sets the value of the emailTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailTypeName(String value) {
        this.emailTypeName = value;
    }

    /**
     * Gets the value of the emailTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailTypeDescription() {
        return emailTypeDescription;
    }

    /**
     * Sets the value of the emailTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailTypeDescription(String value) {
        this.emailTypeDescription = value;
    }

    /**
     * Gets the value of the preferredEmailIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreferredEmailIndicator() {
        return preferredEmailIndicator;
    }

    /**
     * Sets the value of the preferredEmailIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreferredEmailIndicator(Boolean value) {
        this.preferredEmailIndicator = value;
    }

    /**
     * Gets the value of the contactOrderPreferenceTypeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContactOrderPreferenceTypeNumber() {
        return contactOrderPreferenceTypeNumber;
    }

    /**
     * Sets the value of the contactOrderPreferenceTypeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContactOrderPreferenceTypeNumber(BigInteger value) {
        this.contactOrderPreferenceTypeNumber = value;
    }

    /**
     * Gets the value of the usageTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageTypeName() {
        return usageTypeName;
    }

    /**
     * Sets the value of the usageTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageTypeName(String value) {
        this.usageTypeName = value;
    }

    /**
     * Gets the value of the contactModePreferenceTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactModePreferenceTypeName() {
        return contactModePreferenceTypeName;
    }

    /**
     * Sets the value of the contactModePreferenceTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactModePreferenceTypeName(String value) {
        this.contactModePreferenceTypeName = value;
    }

}
