//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package chubb_corporate.business.get_access_user_profile_management_ebe4x1_http;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "GetAccessUserProfileManagementEBE4X1HttpService", targetNamespace = "http://chubb_corporate/business/get_access_user_profile_management_ebe4x1_http", wsdlLocation = "META-INF/wsdl/GetAccessUserProfileManagementEBE4X1Http.wsdl")
public class GetAccessUserProfileManagementEBE4X1HttpService
    extends Service
{

    private final static URL GETACCESSUSERPROFILEMANAGEMENTEBE4X1HTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(chubb_corporate.business.get_access_user_profile_management_ebe4x1_http.GetAccessUserProfileManagementEBE4X1HttpService.class.getName());

    static {
        URL url = null;
        try {
            url = chubb_corporate.business.get_access_user_profile_management_ebe4x1_http.GetAccessUserProfileManagementEBE4X1HttpService.class.getResource("/META-INF/wsdl/GetAccessUserProfileManagementEBE4X1Http.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/GetAccessUserProfileManagementEBE4X1Http.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/GetAccessUserProfileManagementEBE4X1Http.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GETACCESSUSERPROFILEMANAGEMENTEBE4X1HTTPSERVICE_WSDL_LOCATION = url;
    }

    public GetAccessUserProfileManagementEBE4X1HttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAccessUserProfileManagementEBE4X1HttpService() {
        super(GETACCESSUSERPROFILEMANAGEMENTEBE4X1HTTPSERVICE_WSDL_LOCATION, new QName("http://chubb_corporate/business/get_access_user_profile_management_ebe4x1_http", "GetAccessUserProfileManagementEBE4X1HttpService"));
    }

    /**
     * 
     * @return
     *     returns GetAccessUserProfileManagementEBE4X1
     */
    @WebEndpoint(name = "GetAccessUserProfileManagementEBE4X1HTTP_GetAccessUserProfileManagementEBE4X1HttpPort")
    public GetAccessUserProfileManagementEBE4X1 getGetAccessUserProfileManagementEBE4X1HTTPGetAccessUserProfileManagementEBE4X1HttpPort() {
        return super.getPort(new QName("http://chubb_corporate/business/get_access_user_profile_management_ebe4x1_http", "GetAccessUserProfileManagementEBE4X1HTTP_GetAccessUserProfileManagementEBE4X1HttpPort"), GetAccessUserProfileManagementEBE4X1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAccessUserProfileManagementEBE4X1
     */
    @WebEndpoint(name = "GetAccessUserProfileManagementEBE4X1HTTP_GetAccessUserProfileManagementEBE4X1HttpPort")
    public GetAccessUserProfileManagementEBE4X1 getGetAccessUserProfileManagementEBE4X1HTTPGetAccessUserProfileManagementEBE4X1HttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://chubb_corporate/business/get_access_user_profile_management_ebe4x1_http", "GetAccessUserProfileManagementEBE4X1HTTP_GetAccessUserProfileManagementEBE4X1HttpPort"), GetAccessUserProfileManagementEBE4X1.class, features);
    }

}
