//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ei/product/get_filtered_product_list_request_pdt1x1")
package ei.product.get_filtered_product_list_request_pdt1x1;
