//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.prdct_compnt_cross_reference;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This entity is used to relate a Product Component in the Product Catalog to its identifier in another system.
 * 
 * 
 * <p>Java class for PrdctCompntCrossReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrdctCompntCrossReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExternalSystemTableGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExternalSystemTableName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SourceSystemProductComponentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SystemId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrdctCompntCrossReference", namespace = "http://ei/core/prdct_compnt_cross_reference", propOrder = {
    "externalSystemTableGIN",
    "externalSystemTableName",
    "sourceSystemProductComponentId",
    "systemId"
})
public class PrdctCompntCrossReference {

    @XmlElement(name = "ExternalSystemTableGIN")
    protected String externalSystemTableGIN;
    @XmlElement(name = "ExternalSystemTableName")
    protected String externalSystemTableName;
    @XmlElement(name = "SourceSystemProductComponentId")
    protected String sourceSystemProductComponentId;
    @XmlElement(name = "SystemId")
    protected String systemId;

    /**
     * Gets the value of the externalSystemTableGIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalSystemTableGIN() {
        return externalSystemTableGIN;
    }

    /**
     * Sets the value of the externalSystemTableGIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalSystemTableGIN(String value) {
        this.externalSystemTableGIN = value;
    }

    /**
     * Gets the value of the externalSystemTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalSystemTableName() {
        return externalSystemTableName;
    }

    /**
     * Sets the value of the externalSystemTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalSystemTableName(String value) {
        this.externalSystemTableName = value;
    }

    /**
     * Gets the value of the sourceSystemProductComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemProductComponentId() {
        return sourceSystemProductComponentId;
    }

    /**
     * Sets the value of the sourceSystemProductComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemProductComponentId(String value) {
        this.sourceSystemProductComponentId = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

}
