<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/corporate/contact_retrieval_crp30x1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/corporate/contact_retrieval_crp30x1_http" name="ContactRetrievalCRP30X1Http" targetNamespace="http://ei/corporate/contact_retrieval_crp30x1_http">
  <wsdl:import location="ContactRetrievalCRP30X1.wsdl" namespace="http://ei/corporate/contact_retrieval_crp30x1" />
  <wsdl:binding name="ContactRetrievalCRP30X1HttpBinding" type="Port_0:ContactRetrievalCRP30X1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetPolicyContactList">
      <soap:operation soapAction="GetPolicyContactList" />
      <wsdl:input name="GetPolicyContactListRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetPolicyContactListResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetDefaultContact">
      <soap:operation soapAction="GetDefaultContact" />
      <wsdl:input name="GetDefaultContactRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetDefaultContactResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
        <wsdl:operation name="GetPolicyContactListByDefinedRole">
      <soap:operation soapAction="GetPolicyContactListByDefinedRole" />
      <wsdl:input name="GetPolicyContactListByDefinedRoleRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetPolicyContactListByDefinedRoleResponse">
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ContactRetrievalCRP30X1HttpService">
    <wsdl:port binding="this:ContactRetrievalCRP30X1HttpBinding" name="ContactRetrievalCRP30X1HTTP_ContactRetrievalCRP30X1HttpPort">
      <soap:address location="Contact ICC for ContactRetrievalCRP30X1 Endpoint" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>