//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.reporting.commercial_policy_book_of_business_reporting_rpt3x1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ei.reporting.generate_book_of_business_report_reply_rpt3x1.GenerateBookOfBusinessReportReply;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GenerateBookOfBusinessReportReply" type="{http://ei/reporting/generate_book_of_business_report_reply_rpt3x1}GenerateBookOfBusinessReportReply"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generateBookOfBusinessReportReply"
})
@XmlRootElement(name = "GenerateBookOfBusinessReportResponse")
public class GenerateBookOfBusinessReportResponse {

    @XmlElement(name = "GenerateBookOfBusinessReportReply", required = true, nillable = true)
    protected GenerateBookOfBusinessReportReply generateBookOfBusinessReportReply;

    /**
     * Gets the value of the generateBookOfBusinessReportReply property.
     * 
     * @return
     *     possible object is
     *     {@link GenerateBookOfBusinessReportReply }
     *     
     */
    public GenerateBookOfBusinessReportReply getGenerateBookOfBusinessReportReply() {
        return generateBookOfBusinessReportReply;
    }

    /**
     * Sets the value of the generateBookOfBusinessReportReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenerateBookOfBusinessReportReply }
     *     
     */
    public void setGenerateBookOfBusinessReportReply(GenerateBookOfBusinessReportReply value) {
        this.generateBookOfBusinessReportReply = value;
    }

}
