//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.reporting.commercial_policy_book_of_business_reporting_rpt3x1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ei.core.simplefault.SimpleFault;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ei.reporting.commercial_policy_book_of_business_reporting_rpt3x1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SimpleFaultReply_QNAME = new QName("http://ei/reporting/commercial_policy_book_of_business_reporting_rpt3x1", "SimpleFaultReply");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ei.reporting.commercial_policy_book_of_business_reporting_rpt3x1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerateBookOfBusinessReportResponse }
     * 
     */
    public GenerateBookOfBusinessReportResponse createGenerateBookOfBusinessReportResponse() {
        return new GenerateBookOfBusinessReportResponse();
    }

    /**
     * Create an instance of {@link GenerateBookOfBusinessReport }
     * 
     */
    public GenerateBookOfBusinessReport createGenerateBookOfBusinessReport() {
        return new GenerateBookOfBusinessReport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ei/reporting/commercial_policy_book_of_business_reporting_rpt3x1", name = "SimpleFaultReply")
    public JAXBElement<SimpleFault> createSimpleFaultReply(SimpleFault value) {
        return new JAXBElement<SimpleFault>(_SimpleFaultReply_QNAME, SimpleFault.class, null, value);
    }

}
