//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ei/reporting/commercial_policy_book_of_business_reporting_rpt3x1")
package ei.reporting.commercial_policy_book_of_business_reporting_rpt3x1;
