//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.typed_address;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.standardized_addressx3.StandardizedAddress;


/**
 * <p>Java class for TypedAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypedAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StandardizedAddress" type="{http://ei/core/standardized_addressx3}StandardizedAddress" minOccurs="0"/>
 *         &lt;element name="SourceSystemAddressId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressDefaultIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AddressValidatedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PreferredAddressIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContactOrderPreferenceTypeNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="UsageTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactModePreferenceTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypedAddress", namespace = "http://ei/core/typed_address", propOrder = {
    "standardizedAddress",
    "sourceSystemAddressId",
    "addressTypeName",
    "addressTypeDescription",
    "addressDefaultIndicator",
    "addressValidatedIndicator",
    "preferredAddressIndicator",
    "contactOrderPreferenceTypeNumber",
    "usageTypeName",
    "contactModePreferenceTypeName"
})
public class TypedAddress {

    @XmlElement(name = "StandardizedAddress")
    protected StandardizedAddress standardizedAddress;
    @XmlElement(name = "SourceSystemAddressId")
    protected String sourceSystemAddressId;
    @XmlElement(name = "AddressTypeName")
    protected String addressTypeName;
    @XmlElement(name = "AddressTypeDescription")
    protected String addressTypeDescription;
    @XmlElement(name = "AddressDefaultIndicator")
    protected Boolean addressDefaultIndicator;
    @XmlElement(name = "AddressValidatedIndicator")
    protected Boolean addressValidatedIndicator;
    @XmlElement(name = "PreferredAddressIndicator")
    protected Boolean preferredAddressIndicator;
    @XmlElement(name = "ContactOrderPreferenceTypeNumber")
    protected BigInteger contactOrderPreferenceTypeNumber;
    @XmlElement(name = "UsageTypeName")
    protected String usageTypeName;
    @XmlElement(name = "ContactModePreferenceTypeName")
    protected String contactModePreferenceTypeName;

    /**
     * Gets the value of the standardizedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link StandardizedAddress }
     *     
     */
    public StandardizedAddress getStandardizedAddress() {
        return standardizedAddress;
    }

    /**
     * Sets the value of the standardizedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardizedAddress }
     *     
     */
    public void setStandardizedAddress(StandardizedAddress value) {
        this.standardizedAddress = value;
    }

    /**
     * Gets the value of the sourceSystemAddressId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemAddressId() {
        return sourceSystemAddressId;
    }

    /**
     * Sets the value of the sourceSystemAddressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemAddressId(String value) {
        this.sourceSystemAddressId = value;
    }

    /**
     * Gets the value of the addressTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressTypeName() {
        return addressTypeName;
    }

    /**
     * Sets the value of the addressTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressTypeName(String value) {
        this.addressTypeName = value;
    }

    /**
     * Gets the value of the addressTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressTypeDescription() {
        return addressTypeDescription;
    }

    /**
     * Sets the value of the addressTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressTypeDescription(String value) {
        this.addressTypeDescription = value;
    }

    /**
     * Gets the value of the addressDefaultIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddressDefaultIndicator() {
        return addressDefaultIndicator;
    }

    /**
     * Sets the value of the addressDefaultIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddressDefaultIndicator(Boolean value) {
        this.addressDefaultIndicator = value;
    }

    /**
     * Gets the value of the addressValidatedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddressValidatedIndicator() {
        return addressValidatedIndicator;
    }

    /**
     * Sets the value of the addressValidatedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddressValidatedIndicator(Boolean value) {
        this.addressValidatedIndicator = value;
    }

    /**
     * Gets the value of the preferredAddressIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreferredAddressIndicator() {
        return preferredAddressIndicator;
    }

    /**
     * Sets the value of the preferredAddressIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreferredAddressIndicator(Boolean value) {
        this.preferredAddressIndicator = value;
    }

    /**
     * Gets the value of the contactOrderPreferenceTypeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContactOrderPreferenceTypeNumber() {
        return contactOrderPreferenceTypeNumber;
    }

    /**
     * Sets the value of the contactOrderPreferenceTypeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContactOrderPreferenceTypeNumber(BigInteger value) {
        this.contactOrderPreferenceTypeNumber = value;
    }

    /**
     * Gets the value of the usageTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageTypeName() {
        return usageTypeName;
    }

    /**
     * Sets the value of the usageTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageTypeName(String value) {
        this.usageTypeName = value;
    }

    /**
     * Gets the value of the contactModePreferenceTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactModePreferenceTypeName() {
        return contactModePreferenceTypeName;
    }

    /**
     * Sets the value of the contactModePreferenceTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactModePreferenceTypeName(String value) {
        this.contactModePreferenceTypeName = value;
    }

}
