//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ei/corporate/get_default_contact_request_crp30x1")
package ei.corporate.get_default_contact_request_crp30x1;
