//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://chubb_corporate/get_access/source_system_user_profile_id")
package chubb_corporate.get_access.source_system_user_profile_id;
