//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.crm.coinsurancex1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Coinsurance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Coinsurance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CoinsuranceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ConinsuranceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CoinsurancePremiumPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ConinsurancePremiumAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoinsuranceCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CoinsurancePolicyReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CoinsuranceCommissionPercent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoinsuranceCommissionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CoinsuranceCancelReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Coinsurance", namespace = "http://ei/crm/coinsurancex1", propOrder = {
    "coinsuranceCode",
    "coninsuranceName",
    "coinsurancePremiumPercent",
    "coninsurancePremiumAmount",
    "coinsuranceCurrencyCode",
    "coinsurancePolicyReferenceNumber",
    "coinsuranceCommissionPercent",
    "coinsuranceCommissionAmount",
    "coinsuranceCancelReasonDescription"
})
public class Coinsurance {

    @XmlElement(name = "CoinsuranceCode")
    protected String coinsuranceCode;
    @XmlElement(name = "ConinsuranceName")
    protected String coninsuranceName;
    @XmlElement(name = "CoinsurancePremiumPercent")
    protected BigDecimal coinsurancePremiumPercent;
    @XmlElement(name = "ConinsurancePremiumAmount")
    protected BigDecimal coninsurancePremiumAmount;
    @XmlElement(name = "CoinsuranceCurrencyCode")
    protected String coinsuranceCurrencyCode;
    @XmlElement(name = "CoinsurancePolicyReferenceNumber")
    protected String coinsurancePolicyReferenceNumber;
    @XmlElement(name = "CoinsuranceCommissionPercent")
    protected BigDecimal coinsuranceCommissionPercent;
    @XmlElement(name = "CoinsuranceCommissionAmount")
    protected BigDecimal coinsuranceCommissionAmount;
    @XmlElement(name = "CoinsuranceCancelReasonDescription")
    protected String coinsuranceCancelReasonDescription;

    /**
     * Gets the value of the coinsuranceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoinsuranceCode() {
        return coinsuranceCode;
    }

    /**
     * Sets the value of the coinsuranceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoinsuranceCode(String value) {
        this.coinsuranceCode = value;
    }

    /**
     * Gets the value of the coninsuranceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConinsuranceName() {
        return coninsuranceName;
    }

    /**
     * Sets the value of the coninsuranceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConinsuranceName(String value) {
        this.coninsuranceName = value;
    }

    /**
     * Gets the value of the coinsurancePremiumPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoinsurancePremiumPercent() {
        return coinsurancePremiumPercent;
    }

    /**
     * Sets the value of the coinsurancePremiumPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoinsurancePremiumPercent(BigDecimal value) {
        this.coinsurancePremiumPercent = value;
    }

    /**
     * Gets the value of the coninsurancePremiumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConinsurancePremiumAmount() {
        return coninsurancePremiumAmount;
    }

    /**
     * Sets the value of the coninsurancePremiumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConinsurancePremiumAmount(BigDecimal value) {
        this.coninsurancePremiumAmount = value;
    }

    /**
     * Gets the value of the coinsuranceCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoinsuranceCurrencyCode() {
        return coinsuranceCurrencyCode;
    }

    /**
     * Sets the value of the coinsuranceCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoinsuranceCurrencyCode(String value) {
        this.coinsuranceCurrencyCode = value;
    }

    /**
     * Gets the value of the coinsurancePolicyReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoinsurancePolicyReferenceNumber() {
        return coinsurancePolicyReferenceNumber;
    }

    /**
     * Sets the value of the coinsurancePolicyReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoinsurancePolicyReferenceNumber(String value) {
        this.coinsurancePolicyReferenceNumber = value;
    }

    /**
     * Gets the value of the coinsuranceCommissionPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoinsuranceCommissionPercent() {
        return coinsuranceCommissionPercent;
    }

    /**
     * Sets the value of the coinsuranceCommissionPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoinsuranceCommissionPercent(BigDecimal value) {
        this.coinsuranceCommissionPercent = value;
    }

    /**
     * Gets the value of the coinsuranceCommissionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoinsuranceCommissionAmount() {
        return coinsuranceCommissionAmount;
    }

    /**
     * Sets the value of the coinsuranceCommissionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoinsuranceCommissionAmount(BigDecimal value) {
        this.coinsuranceCommissionAmount = value;
    }

    /**
     * Gets the value of the coinsuranceCancelReasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoinsuranceCancelReasonDescription() {
        return coinsuranceCancelReasonDescription;
    }

    /**
     * Sets the value of the coinsuranceCancelReasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoinsuranceCancelReasonDescription(String value) {
        this.coinsuranceCancelReasonDescription = value;
    }

}
