//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ei.core.extendedbranch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ei.core.addressx1.Address;
import ei.core.branchx1.Branch;
import ei.core.language.Language;


/**
 * <p>Java class for ExtendedBranch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedBranch">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ei/core/branchx1}Branch">
 *       &lt;sequence>
 *         &lt;element name="MailingAddress" type="{http://ei/core/addressx1}Address" minOccurs="0"/>
 *         &lt;element name="BranchPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BranchFaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ZoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BranchMailingLabelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForeignBranchIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Language" type="{http://ei/core/language}Language" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedBranch", namespace = "http://ei/core/extendedbranch", propOrder = {
    "mailingAddress",
    "branchPhoneNumber",
    "branchFaxNumber",
    "zoneNumber",
    "branchMailingLabelName",
    "foreignBranchIndicator",
    "language"
})
public class ExtendedBranch
    extends Branch
{

    @XmlElement(name = "MailingAddress")
    protected Address mailingAddress;
    @XmlElement(name = "BranchPhoneNumber")
    protected String branchPhoneNumber;
    @XmlElement(name = "BranchFaxNumber")
    protected String branchFaxNumber;
    @XmlElement(name = "ZoneNumber")
    protected String zoneNumber;
    @XmlElement(name = "BranchMailingLabelName")
    protected String branchMailingLabelName;
    @XmlElement(name = "ForeignBranchIndicator")
    protected String foreignBranchIndicator;
    @XmlElement(name = "Language")
    protected Language language;

    /**
     * Gets the value of the mailingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getMailingAddress() {
        return mailingAddress;
    }

    /**
     * Sets the value of the mailingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setMailingAddress(Address value) {
        this.mailingAddress = value;
    }

    /**
     * Gets the value of the branchPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchPhoneNumber() {
        return branchPhoneNumber;
    }

    /**
     * Sets the value of the branchPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchPhoneNumber(String value) {
        this.branchPhoneNumber = value;
    }

    /**
     * Gets the value of the branchFaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchFaxNumber() {
        return branchFaxNumber;
    }

    /**
     * Sets the value of the branchFaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchFaxNumber(String value) {
        this.branchFaxNumber = value;
    }

    /**
     * Gets the value of the zoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneNumber() {
        return zoneNumber;
    }

    /**
     * Sets the value of the zoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneNumber(String value) {
        this.zoneNumber = value;
    }

    /**
     * Gets the value of the branchMailingLabelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchMailingLabelName() {
        return branchMailingLabelName;
    }

    /**
     * Sets the value of the branchMailingLabelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchMailingLabelName(String value) {
        this.branchMailingLabelName = value;
    }

    /**
     * Gets the value of the foreignBranchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignBranchIndicator() {
        return foreignBranchIndicator;
    }

    /**
     * Sets the value of the foreignBranchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignBranchIndicator(String value) {
        this.foreignBranchIndicator = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }
    
    
 
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		if (this.getMailingAddress() !=null)
		sb.append("Mailing Address: " + this.getMailingAddress().toString());
		sb.append(", Branch PhoneNumber: " +this.getBranchPhoneNumber());
		sb.append(", Branch FaxNumber: " +this.getBranchFaxNumber());
		sb.append(", Zone Number: " +this.getZoneNumber());
		sb.append(", Branch MailingLabelName: " +this.getBranchMailingLabelName());
		sb.append(", Foreign Branch Indicator: " +this.getForeignBranchIndicator());
		if (this.getLanguage()!=null)
		sb.append(", Language: " +this.getLanguage().toString());
		
		return sb.toString();
	}

}
